// ============================================================
// 書道場 — 字卡字典（粵拼 + 意思 + 部首）
// 用於自訂題庫產生器嘅自動查詢
// ============================================================

// Compact format: j=jyutping, e=english, z=中文意思, r=radical, rn=radicalName, em=emoji
const CHAR_DICT = {
  // ── 數字 ──
  '一': { j:'jat1', e:'One', z:'數字一', r:'一', rn:'一部', em:'1️⃣' },
  '二': { j:'ji6', e:'Two', z:'數字二', r:'二', rn:'二部', em:'2️⃣' },
  '三': { j:'saam1', e:'Three', z:'數字三', r:'一', rn:'一部', em:'3️⃣' },
  '四': { j:'sei3', e:'Four', z:'數字四', r:'囗', rn:'國字框', em:'4️⃣' },
  '五': { j:'ng5', e:'Five', z:'數字五', r:'一', rn:'一部', em:'5️⃣' },
  '六': { j:'luk6', e:'Six', z:'數字六', r:'八', rn:'八部', em:'6️⃣' },
  '七': { j:'cat1', e:'Seven', z:'數字七', r:'一', rn:'一部', em:'7️⃣' },
  '八': { j:'baat3', e:'Eight', z:'數字八', r:'八', rn:'八部', em:'8️⃣' },
  '九': { j:'gau2', e:'Nine', z:'數字九', r:'乙', rn:'乙部', em:'9️⃣' },
  '十': { j:'sap6', e:'Ten', z:'數字十', r:'十', rn:'十部', em:'🔟' },
  '百': { j:'baak3', e:'Hundred', z:'一百', r:'白', rn:'白部', em:'💯' },
  '千': { j:'cin1', e:'Thousand', z:'一千', r:'十', rn:'十部', em:'🔢' },
  '萬': { j:'maan6', e:'Ten thousand', z:'一萬', r:'艸', rn:'草字頭', em:'🔢' },
  '零': { j:'ling4', e:'Zero', z:'零', r:'雨', rn:'雨部', em:'0️⃣' },

  // ── 基本漢字 ──
  '人': { j:'jan4', e:'Person', z:'人、人類', r:'人', rn:'人部', em:'🧑' },
  '大': { j:'daai6', e:'Big', z:'大嘅、巨大', r:'大', rn:'大部', em:'🔺' },
  '小': { j:'siu2', e:'Small', z:'細嘅、微小', r:'小', rn:'小部', em:'🔹' },
  '上': { j:'soeng5', e:'Up / Above', z:'上面、向上', r:'一', rn:'一部', em:'⬆️' },
  '下': { j:'haa5', e:'Down / Below', z:'下面、向下', r:'一', rn:'一部', em:'⬇️' },
  '中': { j:'zung1', e:'Middle / China', z:'中間、中國', r:'丨', rn:'豎部', em:'🎯' },
  '左': { j:'zo2', e:'Left', z:'左邊', r:'工', rn:'工部', em:'⬅️' },
  '右': { j:'jau6', e:'Right', z:'右邊', r:'口', rn:'口部', em:'➡️' },
  '正': { j:'zing3', e:'Correct / Upright', z:'正確、正直', r:'止', rn:'止部', em:'✅' },
  '不': { j:'bat1', e:'Not', z:'唔係', r:'一', rn:'一部', em:'❌' },
  '天': { j:'tin1', e:'Sky / Heaven', z:'天空', r:'大', rn:'大部', em:'🌤️' },
  '地': { j:'dei6', e:'Earth / Ground', z:'地面', r:'土', rn:'土部', em:'🌍' },
  '年': { j:'nin4', e:'Year', z:'年份', r:'干', rn:'干部', em:'📅' },
  '月': { j:'jyut6', e:'Moon / Month', z:'月亮、月份', r:'月', rn:'月部', em:'🌙' },
  '日': { j:'jat6', e:'Sun / Day', z:'太陽、日子', r:'日', rn:'日部', em:'☀️' },
  '時': { j:'si4', e:'Time / Hour', z:'時間', r:'日', rn:'日部', em:'⏰' },
  '分': { j:'fan1', e:'Minute / Divide', z:'分鐘、分開', r:'刀', rn:'刀部', em:'⏱️' },

  // ── 自然元素 ──
  '山': { j:'saan1', e:'Mountain', z:'山、山脈', r:'山', rn:'山部', em:'⛰️' },
  '水': { j:'seoi2', e:'Water', z:'水、液體', r:'水', rn:'水部', em:'💧' },
  '火': { j:'fo2', e:'Fire', z:'火、火焰', r:'火', rn:'火部', em:'🔥' },
  '木': { j:'muk6', e:'Wood / Tree', z:'木頭、樹木', r:'木', rn:'木部', em:'🌳' },
  '土': { j:'tou2', e:'Earth / Soil', z:'土地、泥土', r:'土', rn:'土部', em:'🟤' },
  '石': { j:'sek6', e:'Stone / Rock', z:'石頭', r:'石', rn:'石部', em:'🪨' },
  '雲': { j:'wan4', e:'Cloud', z:'雲', r:'雨', rn:'雨部', em:'☁️' },
  '風': { j:'fung1', e:'Wind', z:'風、微風', r:'風', rn:'風部', em:'💨' },
  '雨': { j:'jyu5', e:'Rain', z:'落雨、雨水', r:'雨', rn:'雨部', em:'🌧️' },
  '雪': { j:'syut3', e:'Snow', z:'雪、落雪', r:'雨', rn:'雨部', em:'❄️' },
  '雷': { j:'leoi4', e:'Thunder', z:'行雷', r:'雨', rn:'雨部', em:'⚡' },
  '電': { j:'din6', e:'Electricity / Lightning', z:'電、閃電', r:'雨', rn:'雨部', em:'⚡' },
  '海': { j:'hoi2', e:'Sea / Ocean', z:'大海、海洋', r:'水', rn:'三點水', em:'🌊' },
  '河': { j:'ho4', e:'River', z:'河流', r:'水', rn:'三點水', em:'🏞️' },
  '湖': { j:'wu4', e:'Lake', z:'湖泊', r:'水', rn:'三點水', em:'🏞️' },
  '泉': { j:'cyun4', e:'Spring / Fountain', z:'泉水', r:'水', rn:'水部', em:'⛲' },
  '冰': { j:'bing1', e:'Ice', z:'冰', r:'冫', rn:'冰部', em:'🧊' },
  '島': { j:'dou2', e:'Island', z:'島嶼', r:'山', rn:'山部', em:'🏝️' },

  // ── 植物 ──
  '竹': { j:'zuk1', e:'Bamboo', z:'竹子', r:'竹', rn:'竹部', em:'🎋' },
  '花': { j:'faa1', e:'Flower', z:'花朵', r:'艸', rn:'草字頭', em:'🌸' },
  '草': { j:'cou2', e:'Grass', z:'草、草地', r:'艸', rn:'草字頭', em:'🌿' },
  '林': { j:'lam4', e:'Forest', z:'樹林、森林', r:'木', rn:'木部', em:'🌲' },
  '森': { j:'sam1', e:'Dense forest', z:'森林', r:'木', rn:'木部', em:'🌲' },
  '葉': { j:'jip6', e:'Leaf', z:'樹葉', r:'艸', rn:'草字頭', em:'🍃' },
  '根': { j:'gan1', e:'Root', z:'根部', r:'木', rn:'木部', em:'🌱' },
  '果': { j:'gwo2', e:'Fruit', z:'果實', r:'木', rn:'木部', em:'🍎' },
  '梅': { j:'mui4', e:'Plum', z:'梅花', r:'木', rn:'木部', em:'🌺' },
  '松': { j:'cung4', e:'Pine', z:'松樹', r:'木', rn:'木部', em:'🌲' },
  '蘭': { j:'laan4', e:'Orchid', z:'蘭花', r:'艸', rn:'草字頭', em:'🌷' },
  '菊': { j:'guk1', e:'Chrysanthemum', z:'菊花', r:'艸', rn:'草字頭', em:'🌼' },
  '荷': { j:'ho4', e:'Lotus', z:'荷花', r:'艸', rn:'草字頭', em:'🪷' },
  '茶': { j:'caa4', e:'Tea', z:'茶', r:'艸', rn:'草字頭', em:'🍵' },
  '米': { j:'mai5', e:'Rice', z:'米飯', r:'米', rn:'米部', em:'🍚' },
  '麥': { j:'mak6', e:'Wheat', z:'小麥', r:'麥', rn:'麥部', em:'🌾' },

  // ── 動物 ──
  '馬': { j:'maa5', e:'Horse', z:'馬', r:'馬', rn:'馬部', em:'🐴' },
  '鳥': { j:'niu5', e:'Bird', z:'雀鳥', r:'鳥', rn:'鳥部', em:'🐦' },
  '魚': { j:'jyu4', e:'Fish', z:'魚類', r:'魚', rn:'魚部', em:'🐟' },
  '犬': { j:'hyun2', e:'Dog', z:'狗', r:'犬', rn:'犬部', em:'🐕' },
  '狗': { j:'gau2', e:'Dog', z:'狗', r:'犬', rn:'犬部', em:'🐕' },
  '貓': { j:'maau1', e:'Cat', z:'貓', r:'豸', rn:'豸部', em:'🐱' },
  '牛': { j:'ngau4', e:'Cow / Ox', z:'牛', r:'牛', rn:'牛部', em:'🐂' },
  '羊': { j:'joeng4', e:'Sheep / Goat', z:'羊', r:'羊', rn:'羊部', em:'🐑' },
  '豬': { j:'zyu1', e:'Pig', z:'豬', r:'豕', rn:'豕部', em:'🐷' },
  '雞': { j:'gai1', e:'Chicken', z:'雞', r:'隹', rn:'隹部', em:'🐔' },
  '鴨': { j:'aap3', e:'Duck', z:'鴨', r:'鳥', rn:'鳥部', em:'🦆' },
  '蛇': { j:'se4', e:'Snake', z:'蛇', r:'虫', rn:'虫部', em:'🐍' },
  '龜': { j:'gwai1', e:'Turtle', z:'烏龜', r:'龜', rn:'龜部', em:'🐢' },
  '虎': { j:'fu2', e:'Tiger', z:'老虎', r:'虍', rn:'虎部', em:'🐅' },
  '龍': { j:'lung4', e:'Dragon', z:'龍、神龍', r:'龍', rn:'龍部', em:'🐉' },
  '鳳': { j:'fung6', e:'Phoenix', z:'鳳凰', r:'鳥', rn:'鳥部', em:'🦅' },
  '象': { j:'zoeng6', e:'Elephant', z:'大象', r:'豕', rn:'豕部', em:'🐘' },
  '鹿': { j:'luk6', e:'Deer', z:'鹿', r:'鹿', rn:'鹿部', em:'🦌' },
  '兔': { j:'tou3', e:'Rabbit', z:'兔仔', r:'儿', rn:'兒部', em:'🐇' },
  '熊': { j:'hung4', e:'Bear', z:'熊', r:'火', rn:'火部', em:'🐻' },
  '鶴': { j:'hok6', e:'Crane', z:'白鶴', r:'鳥', rn:'鳥部', em:'🦢' },
  '蝶': { j:'dip6', e:'Butterfly', z:'蝴蝶', r:'虫', rn:'虫部', em:'🦋' },

  // ── 身體 ──
  '口': { j:'hau2', e:'Mouth', z:'嘴巴、口', r:'口', rn:'口部', em:'👄' },
  '手': { j:'sau2', e:'Hand', z:'手、手掌', r:'手', rn:'手部', em:'✋' },
  '目': { j:'muk6', e:'Eye', z:'眼睛', r:'目', rn:'目部', em:'👁️' },
  '耳': { j:'ji5', e:'Ear', z:'耳仔', r:'耳', rn:'耳部', em:'👂' },
  '心': { j:'sam1', e:'Heart / Mind', z:'心臟、心靈', r:'心', rn:'心部', em:'💗' },
  '足': { j:'zuk1', e:'Foot', z:'腳', r:'足', rn:'足部', em:'🦶' },
  '頭': { j:'tau4', e:'Head', z:'頭', r:'頁', rn:'頁部', em:'🗣️' },
  '身': { j:'san1', e:'Body', z:'身體', r:'身', rn:'身部', em:'🧍' },
  '面': { j:'min6', e:'Face', z:'面', r:'面', rn:'面部', em:'😊' },
  '骨': { j:'gwat1', e:'Bone', z:'骨頭', r:'骨', rn:'骨部', em:'🦴' },
  '血': { j:'hyut3', e:'Blood', z:'血', r:'血', rn:'血部', em:'🩸' },
  '肉': { j:'juk6', e:'Meat / Flesh', z:'肉', r:'肉', rn:'肉部', em:'🥩' },
  '齒': { j:'ci2', e:'Teeth', z:'牙齒', r:'齒', rn:'齒部', em:'🦷' },
  '舌': { j:'sit6', e:'Tongue', z:'脷', r:'舌', rn:'舌部', em:'👅' },
  '毛': { j:'mou4', e:'Hair / Fur', z:'毛髮', r:'毛', rn:'毛部', em:'💇' },

  // ── 家庭 ──
  '父': { j:'fu6', e:'Father', z:'爸爸', r:'父', rn:'父部', em:'👨' },
  '母': { j:'mou5', e:'Mother', z:'媽媽', r:'母', rn:'母部', em:'👩' },
  '兒': { j:'ji4', e:'Son / Child', z:'兒子', r:'儿', rn:'兒部', em:'👦' },
  '女': { j:'neoi5', e:'Woman / Girl', z:'女仔', r:'女', rn:'女部', em:'👧' },
  '子': { j:'zi2', e:'Son / Child', z:'子女', r:'子', rn:'子部', em:'👶' },
  '弟': { j:'dai6', e:'Younger brother', z:'細佬', r:'弓', rn:'弓部', em:'👦' },
  '兄': { j:'hing1', e:'Elder brother', z:'大佬', r:'儿', rn:'兒部', em:'👨' },
  '姐': { j:'ze2', e:'Elder sister', z:'家姐', r:'女', rn:'女部', em:'👩' },
  '妹': { j:'mui6', e:'Younger sister', z:'細妹', r:'女', rn:'女部', em:'👧' },
  '夫': { j:'fu1', e:'Husband', z:'丈夫', r:'大', rn:'大部', em:'👨' },
  '妻': { j:'cai1', e:'Wife', z:'妻子', r:'女', rn:'女部', em:'👩' },
  '家': { j:'gaa1', e:'Home / Family', z:'屋企、家庭', r:'宀', rn:'寶蓋頭', em:'🏠' },
  '友': { j:'jau5', e:'Friend', z:'朋友', r:'又', rn:'又部', em:'🤝' },
  '老': { j:'lou5', e:'Old / Elder', z:'老、年紀大', r:'老', rn:'老部', em:'👴' },

  // ── 四季天氣 ──
  '春': { j:'ceon1', e:'Spring', z:'春天', r:'日', rn:'日部', em:'🌱' },
  '夏': { j:'haa6', e:'Summer', z:'夏天', r:'夊', rn:'夂部', em:'☀️' },
  '秋': { j:'cau1', e:'Autumn', z:'秋天', r:'禾', rn:'禾部', em:'🍂' },
  '冬': { j:'dung1', e:'Winter', z:'冬天', r:'冫', rn:'冰部', em:'⛄' },
  '晴': { j:'cing4', e:'Sunny / Clear', z:'晴天', r:'日', rn:'日部', em:'☀️' },
  '暖': { j:'nyun5', e:'Warm', z:'暖', r:'日', rn:'日部', em:'🌡️' },
  '寒': { j:'hon4', e:'Cold', z:'寒冷', r:'宀', rn:'寶蓋頭', em:'🥶' },
  '霧': { j:'mou6', e:'Fog', z:'霧', r:'雨', rn:'雨部', em:'🌫️' },
  '霜': { j:'soeng1', e:'Frost', z:'霜', r:'雨', rn:'雨部', em:'❄️' },
  '露': { j:'lou6', e:'Dew', z:'露水', r:'雨', rn:'雨部', em:'💧' },
  '虹': { j:'hung4', e:'Rainbow', z:'彩虹', r:'虫', rn:'虫部', em:'🌈' },

  // ── 顏色 ──
  '白': { j:'baak6', e:'White', z:'白色', r:'白', rn:'白部', em:'⬜' },
  '黑': { j:'hak1', e:'Black', z:'黑色', r:'黑', rn:'黑部', em:'⬛' },
  '紅': { j:'hung4', e:'Red', z:'紅色', r:'糸', rn:'絲旁', em:'🔴' },
  '青': { j:'cing1', e:'Blue-green', z:'青色', r:'青', rn:'青部', em:'🟢' },
  '黃': { j:'wong4', e:'Yellow', z:'黃色', r:'黃', rn:'黃部', em:'🟡' },
  '金': { j:'gam1', e:'Gold / Metal', z:'金屬、黃金', r:'金', rn:'金部', em:'🥇' },
  '銀': { j:'ngan4', e:'Silver', z:'銀色', r:'金', rn:'金部', em:'🪙' },
  '藍': { j:'laam4', e:'Blue', z:'藍色', r:'艸', rn:'草字頭', em:'🔵' },
  '綠': { j:'luk6', e:'Green', z:'綠色', r:'糸', rn:'絲旁', em:'🟢' },
  '紫': { j:'zi2', e:'Purple', z:'紫色', r:'糸', rn:'絲旁', em:'🟣' },

  // ── 食物相關 ──
  '食': { j:'sik6', e:'Food / Eat', z:'食物、食嘢', r:'食', rn:'食部', em:'🍚' },
  '飯': { j:'faan6', e:'Rice / Meal', z:'飯', r:'食', rn:'食部', em:'🍚' },
  '麵': { j:'min6', e:'Noodles', z:'麵條', r:'麥', rn:'麥部', em:'🍜' },
  '酒': { j:'zau2', e:'Wine / Alcohol', z:'酒', r:'酉', rn:'酉部', em:'🍶' },
  '醬': { j:'zoeng3', e:'Sauce', z:'醬', r:'酉', rn:'酉部', em:'🫙' },
  '鹽': { j:'jim4', e:'Salt', z:'鹽', r:'鹵', rn:'鹵部', em:'🧂' },
  '糖': { j:'tong4', e:'Sugar / Candy', z:'糖', r:'米', rn:'米部', em:'🍬' },
  '豆': { j:'dau6', e:'Bean', z:'豆', r:'豆', rn:'豆部', em:'🫘' },
  '瓜': { j:'gwaa1', e:'Melon', z:'瓜', r:'瓜', rn:'瓜部', em:'🍈' },
  '餅': { j:'beng2', e:'Cake / Biscuit', z:'餅', r:'食', rn:'食部', em:'🥮' },

  // ── 建築空間 ──
  '門': { j:'mun4', e:'Door / Gate', z:'門、大門', r:'門', rn:'門部', em:'🚪' },
  '窗': { j:'coeng1', e:'Window', z:'窗', r:'穴', rn:'穴部', em:'🪟' },
  '屋': { j:'uk1', e:'House', z:'屋企', r:'尸', rn:'尸部', em:'🏠' },
  '樓': { j:'lau4', e:'Building / Floor', z:'大樓', r:'木', rn:'木部', em:'🏢' },
  '城': { j:'sing4', e:'City / Castle', z:'城市', r:'土', rn:'土部', em:'🏙️' },
  '橋': { j:'kiu4', e:'Bridge', z:'橋', r:'木', rn:'木部', em:'🌉' },
  '路': { j:'lou6', e:'Road / Path', z:'道路', r:'足', rn:'足部', em:'🛤️' },
  '街': { j:'gaai1', e:'Street', z:'街道', r:'行', rn:'行部', em:'🏘️' },
  '塔': { j:'taap3', e:'Tower / Pagoda', z:'塔', r:'土', rn:'土部', em:'🗼' },
  '宮': { j:'gung1', e:'Palace', z:'宮殿', r:'宀', rn:'寶蓋頭', em:'🏯' },
  '殿': { j:'din6', e:'Hall / Palace', z:'殿堂', r:'殳', rn:'殳部', em:'🏛️' },
  '廟': { j:'miu6', e:'Temple', z:'廟宇', r:'广', rn:'广部', em:'⛩️' },
  '園': { j:'jyun4', e:'Garden / Park', z:'公園', r:'囗', rn:'國字框', em:'🏞️' },

  // ── 田野農業 ──
  '田': { j:'tin4', e:'Field', z:'田地、農田', r:'田', rn:'田部', em:'🌾' },

  // ── 王者 ──
  '王': { j:'wong4', e:'King', z:'國王、王者', r:'王', rn:'王部', em:'👑' },
  '皇': { j:'wong4', e:'Emperor', z:'皇帝', r:'白', rn:'白部', em:'👑' },
  '帝': { j:'dai3', e:'Emperor', z:'皇帝', r:'巾', rn:'巾部', em:'👑' },

  // ── 天文地理 ──
  '星': { j:'sing1', e:'Star', z:'星星、星辰', r:'日', rn:'日部', em:'⭐' },
  '光': { j:'gwong1', e:'Light', z:'光芒、光明', r:'儿', rn:'兒部', em:'💡' },
  '夜': { j:'je6', e:'Night', z:'夜晚', r:'夕', rn:'夕部', em:'🌙' },
  '朝': { j:'ziu1', e:'Morning / Dynasty', z:'朝早', r:'月', rn:'月部', em:'🌅' },
  '暮': { j:'mou6', e:'Evening / Dusk', z:'黃昏', r:'日', rn:'日部', em:'🌇' },
  '明': { j:'ming4', e:'Bright / Clear', z:'光明', r:'日', rn:'日部', em:'🔆' },
  '暗': { j:'am3', e:'Dark', z:'黑暗', r:'日', rn:'日部', em:'🌑' },
  '影': { j:'jing2', e:'Shadow', z:'影子', r:'彡', rn:'彡部', em:'👤' },
  '空': { j:'hung1', e:'Sky / Empty', z:'天空、空虛', r:'穴', rn:'穴部', em:'🌌' },

  // ── 武道精神 ──
  '道': { j:'dou6', e:'Way / Path', z:'道路、道理', r:'辶', rn:'走之底', em:'☯️' },
  '義': { j:'ji6', e:'Righteousness', z:'正義、道義', r:'羊', rn:'羊部', em:'⚖️' },
  '禮': { j:'lai5', e:'Ritual / Politeness', z:'禮貌、禮儀', r:'示', rn:'示部', em:'🙏' },
  '智': { j:'zi3', e:'Wisdom', z:'智慧、聰明', r:'日', rn:'日部', em:'🧠' },
  '勇': { j:'jung5', e:'Courage / Brave', z:'勇敢、勇氣', r:'力', rn:'力部', em:'💪' },
  '德': { j:'dak1', e:'Virtue / Morality', z:'品德、道德', r:'彳', rn:'雙人旁', em:'🌟' },
  '師': { j:'si1', e:'Master / Teacher', z:'老師、師傅', r:'巾', rn:'巾部', em:'👨‍🏫' },
  '學': { j:'hok6', e:'Study / Learn', z:'學習、學問', r:'子', rn:'子部', em:'📚' },
  '愛': { j:'oi3', e:'Love', z:'愛、鍾意', r:'心', rn:'心部', em:'❤️' },
  '夢': { j:'mung6', e:'Dream', z:'夢想、發夢', r:'夕', rn:'夕部', em:'💭' },
  '劍': { j:'gim3', e:'Sword', z:'寶劍、劍術', r:'刀', rn:'立刀旁', em:'⚔️' },
  '書': { j:'syu1', e:'Book / Writing', z:'書法、書本', r:'曰', rn:'曰部', em:'📖' },
  '畫': { j:'waa2', e:'Painting / Drawing', z:'繪畫、圖畫', r:'田', rn:'田部', em:'🎨' },
  '武': { j:'mou5', e:'Martial / Military', z:'武術、武道', r:'止', rn:'止部', em:'🥋' },
  '藝': { j:'ngai6', e:'Art / Skill', z:'藝術、技藝', r:'艸', rn:'草字頭', em:'🎭' },
  '戰': { j:'zin3', e:'Battle / War', z:'戰鬥、挑戰', r:'戈', rn:'戈部', em:'⚔️' },
  '練': { j:'lin6', e:'Practice / Train', z:'練習、訓練', r:'糸', rn:'絲旁', em:'🔄' },
  '國': { j:'gwok3', e:'Country / Nation', z:'國家', r:'囗', rn:'國字框', em:'🏯' },
  '寶': { j:'bou2', e:'Treasure', z:'寶物、珍寶', r:'宀', rn:'寶蓋頭', em:'💎' },
  '力': { j:'lik6', e:'Power / Strength', z:'力量、力氣', r:'力', rn:'力部', em:'⚡' },
  '氣': { j:'hei3', e:'Air / Energy', z:'氣、力氣', r:'气', rn:'气部', em:'💨' },
  '拳': { j:'kyun4', e:'Fist', z:'拳頭', r:'手', rn:'手部', em:'👊' },
  '刀': { j:'dou1', e:'Knife / Blade', z:'刀', r:'刀', rn:'刀部', em:'🔪' },
  '弓': { j:'gung1', e:'Bow', z:'弓', r:'弓', rn:'弓部', em:'🏹' },
  '箭': { j:'zin3', e:'Arrow', z:'箭', r:'竹', rn:'竹部', em:'🏹' },
  '盾': { j:'teon5', e:'Shield', z:'盾牌', r:'目', rn:'目部', em:'🛡️' },
  '甲': { j:'gaap3', e:'Armor', z:'盔甲', r:'田', rn:'田部', em:'🛡️' },

  // ── 品德情感 ──
  '仁': { j:'jan4', e:'Benevolence', z:'仁慈', r:'人', rn:'人部', em:'💛' },
  '信': { j:'seon3', e:'Trust / Letter', z:'信任、書信', r:'人', rn:'人部', em:'📨' },
  '忠': { j:'zung1', e:'Loyalty', z:'忠誠', r:'心', rn:'心部', em:'💙' },
  '孝': { j:'haau3', e:'Filial piety', z:'孝順', r:'子', rn:'子部', em:'🙏' },
  '善': { j:'sin6', e:'Good / Kind', z:'善良', r:'口', rn:'口部', em:'😇' },
  '惡': { j:'ok3', e:'Evil / Bad', z:'邪惡', r:'心', rn:'心部', em:'😈' },
  '樂': { j:'lok6', e:'Joy / Music', z:'快樂、音樂', r:'木', rn:'木部', em:'🎵' },
  '哀': { j:'oi1', e:'Sorrow', z:'悲哀', r:'口', rn:'口部', em:'😢' },
  '怒': { j:'nou6', e:'Anger', z:'憤怒', r:'心', rn:'心部', em:'😡' },
  '恐': { j:'hung2', e:'Fear', z:'恐懼', r:'心', rn:'心部', em:'😨' },
  '喜': { j:'hei2', e:'Joy / Happiness', z:'歡喜', r:'口', rn:'口部', em:'😄' },
  '靜': { j:'zing6', e:'Quiet / Calm', z:'寧靜', r:'青', rn:'青部', em:'🧘' },
  '和': { j:'wo4', e:'Peace / Harmony', z:'和平、和諧', r:'口', rn:'口部', em:'☮️' },
  '真': { j:'zan1', e:'True / Real', z:'真實', r:'目', rn:'目部', em:'💯' },
  '美': { j:'mei5', e:'Beautiful', z:'美麗', r:'羊', rn:'羊部', em:'✨' },
  '情': { j:'cing4', e:'Feeling / Love', z:'感情', r:'心', rn:'心部', em:'💕' },
  '恩': { j:'jan1', e:'Grace / Kindness', z:'恩惠', r:'心', rn:'心部', em:'🙏' },
  '慧': { j:'wai6', e:'Wisdom', z:'智慧', r:'心', rn:'心部', em:'🧠' },
  '忍': { j:'jan2', e:'Endure / Patience', z:'忍耐', r:'心', rn:'心部', em:'🧘' },
  '志': { j:'zi3', e:'Ambition / Will', z:'志向', r:'心', rn:'心部', em:'🎯' },
  '意': { j:'ji3', e:'Meaning / Intent', z:'意思', r:'心', rn:'心部', em:'💡' },

  // ── 行動動作 ──
  '走': { j:'zau2', e:'Run / Walk', z:'行走', r:'走', rn:'走部', em:'🏃' },
  '行': { j:'hang4', e:'Walk / Go', z:'行、行走', r:'行', rn:'行部', em:'🚶' },
  '飛': { j:'fei1', e:'Fly', z:'飛', r:'飛', rn:'飛部', em:'✈️' },
  '立': { j:'laap6', e:'Stand', z:'企、站立', r:'立', rn:'立部', em:'🧍' },
  '坐': { j:'co5', e:'Sit', z:'坐', r:'土', rn:'土部', em:'🪑' },
  '見': { j:'gin3', e:'See', z:'見到', r:'見', rn:'見部', em:'👀' },
  '聞': { j:'man4', e:'Hear / Smell', z:'聽到', r:'門', rn:'門部', em:'👂' },
  '言': { j:'jin4', e:'Speech / Word', z:'言語', r:'言', rn:'言部', em:'💬' },
  '說': { j:'syut3', e:'Speak / Say', z:'講嘢', r:'言', rn:'言部', em:'🗣️' },
  '讀': { j:'duk6', e:'Read', z:'讀書', r:'言', rn:'言部', em:'📖' },
  '寫': { j:'se2', e:'Write', z:'寫字', r:'宀', rn:'寶蓋頭', em:'✍️' },
  '打': { j:'daa2', e:'Hit / Strike', z:'打', r:'手', rn:'手部', em:'👊' },
  '開': { j:'hoi1', e:'Open', z:'打開', r:'門', rn:'門部', em:'🔓' },
  '關': { j:'gwaan1', e:'Close / Related', z:'關閉', r:'門', rn:'門部', em:'🔒' },
  '來': { j:'loi4', e:'Come', z:'嚟', r:'人', rn:'人部', em:'🔜' },
  '去': { j:'heoi3', e:'Go', z:'去', r:'厶', rn:'厶部', em:'🔚' },
  '入': { j:'jap6', e:'Enter', z:'入嚟', r:'入', rn:'入部', em:'🚪' },
  '出': { j:'ceot1', e:'Exit / Go out', z:'出去', r:'凵', rn:'凵部', em:'🚪' },
  '生': { j:'saang1', e:'Life / Birth', z:'生命、出世', r:'生', rn:'生部', em:'🌱' },
  '死': { j:'sei2', e:'Death / Die', z:'死亡', r:'歹', rn:'歹部', em:'💀' },
  '給': { j:'kap1', e:'Give', z:'畀', r:'糸', rn:'絲旁', em:'🎁' },
  '教': { j:'gaau3', e:'Teach', z:'教', r:'攴', rn:'攴部', em:'👨‍🏫' },

  // ── 文字文化 ──
  '字': { j:'zi6', e:'Character / Word', z:'文字', r:'子', rn:'子部', em:'🔤' },
  '文': { j:'man4', e:'Writing / Culture', z:'文字、文化', r:'文', rn:'文部', em:'📜' },
  '語': { j:'jyu5', e:'Language', z:'語言', r:'言', rn:'言部', em:'💬' },
  '詩': { j:'si1', e:'Poetry', z:'詩', r:'言', rn:'言部', em:'📝' },
  '詞': { j:'ci4', e:'Lyrics / Word', z:'歌詞', r:'言', rn:'言部', em:'📝' },
  '歌': { j:'go1', e:'Song', z:'歌', r:'欠', rn:'欠部', em:'🎵' },
  '舞': { j:'mou5', e:'Dance', z:'跳舞', r:'舛', rn:'舛部', em:'💃' },
  '琴': { j:'kam4', e:'Zither / Instrument', z:'琴', r:'王', rn:'王部', em:'🎹' },
  '棋': { j:'kei4', e:'Chess', z:'棋', r:'木', rn:'木部', em:'♟️' },
  '筆': { j:'bat1', e:'Pen / Brush', z:'筆', r:'竹', rn:'竹部', em:'🖊️' },
  '墨': { j:'mak6', e:'Ink', z:'墨', r:'土', rn:'土部', em:'🖤' },
  '紙': { j:'zi2', e:'Paper', z:'紙', r:'糸', rn:'絲旁', em:'📄' },
  '硯': { j:'jin6', e:'Inkstone', z:'硯台', r:'石', rn:'石部', em:'🪨' },

  // ── 抽象概念 ──
  '理': { j:'lei5', e:'Reason / Principle', z:'道理', r:'王', rn:'王部', em:'💡' },
  '法': { j:'faat3', e:'Law / Method', z:'法律、方法', r:'水', rn:'三點水', em:'⚖️' },
  '事': { j:'si6', e:'Matter / Thing', z:'事情', r:'亅', rn:'亅部', em:'📋' },
  '物': { j:'mat6', e:'Thing / Object', z:'事物', r:'牛', rn:'牛部', em:'📦' },
  '名': { j:'ming4', e:'Name / Fame', z:'名字', r:'口', rn:'口部', em:'📛' },
  '命': { j:'meng6', e:'Life / Fate', z:'生命、命運', r:'口', rn:'口部', em:'🔮' },
  '思': { j:'si1', e:'Think / Miss', z:'思念', r:'心', rn:'心部', em:'🤔' },
  '想': { j:'soeng2', e:'Think / Want', z:'想', r:'心', rn:'心部', em:'💭' },
  '知': { j:'zi1', e:'Know', z:'知道', r:'矢', rn:'矢部', em:'🧠' },
  '問': { j:'man6', e:'Ask / Question', z:'問題', r:'門', rn:'門部', em:'❓' },
  '答': { j:'daap3', e:'Answer', z:'回答', r:'竹', rn:'竹部', em:'💬' },
  '話': { j:'waa6', e:'Words / Talk', z:'說話', r:'言', rn:'言部', em:'💬' },
  '永': { j:'wing5', e:'Eternal', z:'永恆', r:'水', rn:'水部', em:'♾️' },
  '初': { j:'co1', e:'First / Beginning', z:'最初', r:'刀', rn:'刀部', em:'🌅' },
  '終': { j:'zung1', e:'End / Final', z:'終結', r:'糸', rn:'絲旁', em:'🏁' },
  '始': { j:'ci2', e:'Begin', z:'開始', r:'女', rn:'女部', em:'▶️' },
  '新': { j:'san1', e:'New', z:'新嘅', r:'斤', rn:'斤部', em:'🆕' },
  '古': { j:'gu2', e:'Ancient / Old', z:'古代', r:'口', rn:'口部', em:'🏛️' },
  '今': { j:'gam1', e:'Now / Present', z:'今日', r:'人', rn:'人部', em:'📍' },
  '先': { j:'sin1', e:'First / Before', z:'先', r:'儿', rn:'兒部', em:'1️⃣' },
  '後': { j:'hau6', e:'After / Behind', z:'之後', r:'彳', rn:'雙人旁', em:'🔙' },
  '成': { j:'sing4', e:'Become / Complete', z:'成功', r:'戈', rn:'戈部', em:'✅' },
  '敗': { j:'baai6', e:'Defeat / Fail', z:'失敗', r:'攴', rn:'攴部', em:'❌' },
  '勝': { j:'sing3', e:'Victory / Win', z:'勝利', r:'力', rn:'力部', em:'🏆' },
  '能': { j:'nang4', e:'Ability / Can', z:'能力', r:'肉', rn:'肉部', em:'💪' },

  // ── 方位 ──
  '東': { j:'dung1', e:'East', z:'東面', r:'木', rn:'木部', em:'🌅' },
  '西': { j:'sai1', e:'West', z:'西面', r:'西', rn:'西部', em:'🌇' },
  '南': { j:'naam4', e:'South', z:'南面', r:'十', rn:'十部', em:'🧭' },
  '北': { j:'bak1', e:'North', z:'北面', r:'匕', rn:'匕部', em:'🧭' },
  '前': { j:'cin4', e:'Front / Before', z:'前面', r:'刀', rn:'刀部', em:'⏩' },
  '內': { j:'noi6', e:'Inside', z:'入面', r:'入', rn:'入部', em:'🔲' },
  '外': { j:'ngoi6', e:'Outside', z:'外面', r:'夕', rn:'夕部', em:'🔳' },
  '間': { j:'gaan1', e:'Between / Room', z:'中間', r:'門', rn:'門部', em:'🚪' },

  // ── 常見字 ──
  '的': { j:'dik1', e:'(possessive particle)', z:'嘅', r:'白', rn:'白部', em:'📌' },
  '是': { j:'si6', e:'Is / Yes', z:'係', r:'日', rn:'日部', em:'✅' },
  '有': { j:'jau5', e:'Have', z:'有', r:'月', rn:'月部', em:'✔️' },
  '無': { j:'mou4', e:'None / Without', z:'冇', r:'火', rn:'火部', em:'❌' },
  '也': { j:'jaa5', e:'Also', z:'都', r:'乙', rn:'乙部', em:'➕' },
  '在': { j:'zoi6', e:'At / In', z:'喺', r:'土', rn:'土部', em:'📍' },
  '這': { j:'ze5', e:'This', z:'呢個', r:'辶', rn:'走之底', em:'👉' },
  '那': { j:'naa5', e:'That', z:'嗰個', r:'邑', rn:'邑部', em:'👈' },
  '他': { j:'taa1', e:'He / Him', z:'佢（男）', r:'人', rn:'人部', em:'👨' },
  '她': { j:'taa1', e:'She / Her', z:'佢（女）', r:'女', rn:'女部', em:'👩' },
  '我': { j:'ngo5', e:'I / Me', z:'我', r:'戈', rn:'戈部', em:'🙋' },
  '你': { j:'nei5', e:'You', z:'你', r:'人', rn:'人部', em:'🫵' },
  '們': { j:'mun4', e:'(plural marker)', z:'們（複數）', r:'人', rn:'人部', em:'👥' },
  '好': { j:'hou2', e:'Good', z:'好', r:'女', rn:'女部', em:'👍' },
  '多': { j:'do1', e:'Many / Much', z:'多', r:'夕', rn:'夕部', em:'📊' },
  '少': { j:'siu2', e:'Few / Little', z:'少', r:'小', rn:'小部', em:'📉' },
  '長': { j:'coeng4', e:'Long / Elder', z:'長', r:'長', rn:'長部', em:'📏' },
  '短': { j:'dyun2', e:'Short', z:'短', r:'矢', rn:'矢部', em:'📏' },
  '高': { j:'gou1', e:'Tall / High', z:'高', r:'高', rn:'高部', em:'📈' },
  '深': { j:'sam1', e:'Deep', z:'深', r:'水', rn:'三點水', em:'🌊' },
  '強': { j:'koeng5', e:'Strong', z:'強', r:'弓', rn:'弓部', em:'💪' },
  '弱': { j:'joek6', e:'Weak', z:'弱', r:'弓', rn:'弓部', em:'😔' },
  '快': { j:'faai3', e:'Fast / Happy', z:'快', r:'心', rn:'心部', em:'⚡' },
  '慢': { j:'maan6', e:'Slow', z:'慢', r:'心', rn:'心部', em:'🐌' },
  '難': { j:'naan4', e:'Difficult', z:'難', r:'隹', rn:'隹部', em:'😰' },
  '易': { j:'ji6', e:'Easy', z:'容易', r:'日', rn:'日部', em:'😎' },
  '滿': { j:'mun5', e:'Full', z:'滿', r:'水', rn:'三點水', em:'🈵' },
  '空': { j:'hung1', e:'Empty / Sky', z:'空', r:'穴', rn:'穴部', em:'⭕' },
  '忙': { j:'mong4', e:'Busy', z:'忙碌', r:'心', rn:'心部', em:'😵' },
  '安': { j:'on1', e:'Peace / Safe', z:'平安', r:'宀', rn:'寶蓋頭', em:'☮️' },
  '危': { j:'ngai4', e:'Danger', z:'危險', r:'厄', rn:'厄部', em:'⚠️' },
  '富': { j:'fu3', e:'Rich', z:'富有', r:'宀', rn:'寶蓋頭', em:'💰' },
  '貧': { j:'pan4', e:'Poor', z:'貧窮', r:'貝', rn:'貝部', em:'😢' },

  // ── 社會文明 ──
  '民': { j:'man4', e:'People', z:'民眾', r:'氏', rn:'氏部', em:'👥' },
  '官': { j:'gun1', e:'Official', z:'官員', r:'宀', rn:'寶蓋頭', em:'🏛️' },
  '軍': { j:'gwan1', e:'Army', z:'軍隊', r:'車', rn:'車部', em:'🪖' },
  '將': { j:'zoeng1', e:'General', z:'將軍', r:'寸', rn:'寸部', em:'🎖️' },
  '兵': { j:'bing1', e:'Soldier', z:'士兵', r:'八', rn:'八部', em:'💂' },
  '車': { j:'ce1', e:'Vehicle / Car', z:'車', r:'車', rn:'車部', em:'🚗' },
  '船': { j:'syun4', e:'Ship / Boat', z:'船', r:'舟', rn:'舟部', em:'🚢' },
  '衣': { j:'ji1', e:'Clothes', z:'衫', r:'衣', rn:'衣部', em:'👕' },
  '錢': { j:'cin4', e:'Money', z:'錢', r:'金', rn:'金部', em:'💰' },
  '寺': { j:'zi6', e:'Temple', z:'寺', r:'寸', rn:'寸部', em:'🛕' },
  '佛': { j:'fat6', e:'Buddha', z:'佛', r:'人', rn:'人部', em:'🪷' },
  '神': { j:'san4', e:'God / Spirit', z:'神', r:'示', rn:'示部', em:'✨' },
  '聖': { j:'sing3', e:'Holy / Saint', z:'神聖', r:'耳', rn:'耳部', em:'⭐' },
  '經': { j:'ging1', e:'Classic / Sutra', z:'經典', r:'糸', rn:'絲旁', em:'📜' },
  '雅': { j:'ngaa5', e:'Elegant', z:'優雅', r:'隹', rn:'隹部', em:'🎩' },
  '禪': { j:'sim4', e:'Zen / Meditation', z:'禪', r:'示', rn:'示部', em:'🧘' },

  // ── 更多常用字 ──
  '工': { j:'gung1', e:'Work', z:'工作', r:'工', rn:'工部', em:'🔧' },
  '才': { j:'coi4', e:'Talent', z:'才能', r:'手', rn:'手部', em:'🌟' },
  '之': { j:'zi1', e:'(possessive)', z:'之、嘅', r:'丶', rn:'丶部', em:'📎' },
  '以': { j:'ji5', e:'With / By', z:'以', r:'人', rn:'人部', em:'📎' },
  '令': { j:'ling6', e:'Order / Make', z:'令', r:'人', rn:'人部', em:'📜' },
  '何': { j:'ho4', e:'What / How', z:'乜嘢', r:'人', rn:'人部', em:'❓' },
  '作': { j:'zok3', e:'Do / Make', z:'做', r:'人', rn:'人部', em:'🛠️' },
  '使': { j:'si2', e:'Use / Make', z:'使用', r:'人', rn:'人部', em:'🔧' },
  '然': { j:'jin4', e:'So / Thus', z:'然後', r:'火', rn:'火部', em:'➡️' },
  '而': { j:'ji4', e:'And / But', z:'而且', r:'而', rn:'而部', em:'➕' },
  '為': { j:'wai4', e:'For / Do', z:'為咗', r:'火', rn:'火部', em:'🎯' },
  '所': { j:'so2', e:'Place / That which', z:'所以', r:'戶', rn:'戶部', em:'📍' },
  '與': { j:'jyu5', e:'And / With', z:'同', r:'臼', rn:'臼部', em:'🤝' },
  '此': { j:'ci2', e:'This', z:'呢個', r:'止', rn:'止部', em:'👉' },
  '如': { j:'jyu4', e:'Like / As', z:'好似', r:'女', rn:'女部', em:'🔄' },
  '必': { j:'bit1', e:'Must', z:'必須', r:'心', rn:'心部', em:'❗' },
  '已': { j:'ji5', e:'Already', z:'已經', r:'己', rn:'己部', em:'✅' },
  '又': { j:'jau6', e:'Again / Also', z:'又', r:'又', rn:'又部', em:'🔄' },
  '及': { j:'kap6', e:'Reach / And', z:'及', r:'又', rn:'又部', em:'➕' },
  '但': { j:'daan6', e:'But', z:'但係', r:'人', rn:'人部', em:'↩️' },
  '只': { j:'zi2', e:'Only / Just', z:'只係', r:'口', rn:'口部', em:'☝️' },
  '更': { j:'gang3', e:'More / Even more', z:'更加', r:'曰', rn:'曰部', em:'⬆️' },
  '最': { j:'zeoi3', e:'Most', z:'最', r:'曰', rn:'曰部', em:'🏆' },
  '自': { j:'zi6', e:'Self', z:'自己', r:'自', rn:'自部', em:'🫵' },
  '其': { j:'kei4', e:'That / Its', z:'其', r:'八', rn:'八部', em:'👉' },
  '會': { j:'wui5', e:'Can / Meeting', z:'會', r:'曰', rn:'曰部', em:'🤝' },
  '得': { j:'dak1', e:'Get / OK', z:'得到', r:'彳', rn:'雙人旁', em:'✅' },
  '還': { j:'waan4', e:'Still / Return', z:'仍然', r:'辶', rn:'走之底', em:'🔄' },
  '把': { j:'baa2', e:'Hold / Handle', z:'揸住', r:'手', rn:'手部', em:'✊' },
  '被': { j:'bei6', e:'By (passive)', z:'被', r:'衣', rn:'衣部', em:'📎' },
  '從': { j:'cung4', e:'From / Follow', z:'從', r:'彳', rn:'雙人旁', em:'📍' },
  '讓': { j:'joeng6', e:'Let / Allow', z:'讓', r:'言', rn:'言部', em:'✅' },

  // ── 香港文化 ──
  '港': { j:'gong2', e:'Harbour / Hong Kong', z:'港口、香港', r:'水', rn:'三點水', em:'⛵' },
  '香': { j:'hoeng1', e:'Fragrant / Incense', z:'香', r:'香', rn:'香部', em:'🌸' },
  '粵': { j:'jyut6', e:'Cantonese / Guangdong', z:'粵、廣東', r:'米', rn:'米部', em:'🏮' },
  '嶺': { j:'ling5', e:'Mountain ridge', z:'山嶺', r:'山', rn:'山部', em:'🏔️' },
  '灣': { j:'waan1', e:'Bay', z:'海灣', r:'水', rn:'三點水', em:'🏖️' },
  '龍': { j:'lung4', e:'Dragon', z:'龍、神龍', r:'龍', rn:'龍部', em:'🐉' },
  '鳳': { j:'fung6', e:'Phoenix', z:'鳳凰', r:'鳥', rn:'鳥部', em:'🦅' },
  '福': { j:'fuk1', e:'Blessing / Fortune', z:'福氣', r:'示', rn:'示部', em:'🧧' },
  '壽': { j:'sau6', e:'Longevity', z:'長壽', r:'寸', rn:'寸部', em:'🎂' },
  '喜': { j:'hei2', e:'Joy / Happiness', z:'歡喜', r:'口', rn:'口部', em:'😄' },
  '囍': { j:'hei2', e:'Double happiness', z:'雙喜', r:'口', rn:'口部', em:'🎊' },
  '財': { j:'coi4', e:'Wealth', z:'財富', r:'貝', rn:'貝部', em:'💰' },
  '發': { j:'faat3', e:'Prosper / Send', z:'發達', r:'弓', rn:'弓部', em:'🎆' },
  '吉': { j:'gat1', e:'Luck / Auspicious', z:'吉祥', r:'口', rn:'口部', em:'🍀' },
  '祥': { j:'coeng4', e:'Auspicious', z:'吉祥', r:'示', rn:'示部', em:'✨' },
  '瑞': { j:'seoi6', e:'Lucky / Auspicious', z:'祥瑞', r:'王', rn:'王部', em:'🌈' },
  '鋪': { j:'pou3', e:'Shop', z:'舖頭', r:'金', rn:'金部', em:'🏪' },
  '點': { j:'dim2', e:'Dot / How', z:'點、點心', r:'黑', rn:'黑部', em:'⚫' }
};


// ── 214 康熙部首名稱對照 ──
const RADICAL_NAMES = {
  '一': '一部（橫部）',
  '丨': '豎部',
  '丶': '丶部（點部）',
  '丿': '丿部（撇部）',
  '乙': '乙部',
  '亅': '亅部（鉤部）',
  '二': '二部',
  '亠': '亠部（文字頭）',
  '人': '人部（亻）',
  '儿': '兒部',
  '入': '入部',
  '八': '八部',
  '冂': '冂部',
  '冖': '冖部（禿寶蓋）',
  '冫': '冰部（冫）',
  '几': '几部',
  '凵': '凵部',
  '刀': '刀部（刂）',
  '力': '力部',
  '勹': '勹部',
  '匕': '匕部',
  '匚': '匚部',
  '匸': '匸部',
  '十': '十部',
  '卜': '卜部',
  '卩': '卩部',
  '厂': '厂部',
  '厶': '厶部',
  '又': '又部',
  '口': '口部',
  '囗': '國字框（囗）',
  '土': '土部',
  '士': '士部',
  '夂': '夂部',
  '夊': '夂部',
  '夕': '夕部',
  '大': '大部',
  '女': '女部',
  '子': '子部',
  '宀': '寶蓋頭（宀）',
  '寸': '寸部',
  '小': '小部',
  '尢': '尢部',
  '尸': '尸部',
  '屮': '屮部',
  '山': '山部',
  '巛': '巛部（川部）',
  '工': '工部',
  '己': '己部',
  '巾': '巾部',
  '干': '干部',
  '幺': '幺部',
  '广': '广部',
  '廴': '廴部',
  '廾': '廾部',
  '弋': '弋部',
  '弓': '弓部',
  '彐': '彐部',
  '彡': '彡部',
  '彳': '雙人旁（彳）',
  '心': '心部（忄）',
  '戈': '戈部',
  '戶': '戶部',
  '手': '手部（扌）',
  '支': '支部',
  '攴': '攴部',
  '文': '文部',
  '斗': '斗部',
  '斤': '斤部',
  '方': '方部',
  '無': '無部',
  '日': '日部',
  '曰': '曰部',
  '月': '月部',
  '木': '木部',
  '欠': '欠部',
  '止': '止部',
  '歹': '歹部',
  '殳': '殳部',
  '毋': '毋部',
  '比': '比部',
  '毛': '毛部',
  '氏': '氏部',
  '气': '气部',
  '水': '水部（氵）',
  '火': '火部（灬）',
  '爪': '爪部',
  '父': '父部',
  '爻': '爻部',
  '爿': '爿部',
  '片': '片部',
  '牙': '牙部',
  '牛': '牛部（牜）',
  '犬': '犬部（犭）',
  '玄': '玄部',
  '玉': '玉部（王）',
  '瓜': '瓜部',
  '瓦': '瓦部',
  '甘': '甘部',
  '生': '生部',
  '用': '用部',
  '田': '田部',
  '疋': '疋部',
  '疒': '疒部',
  '癶': '癶部',
  '白': '白部',
  '皮': '皮部',
  '皿': '皿部',
  '目': '目部',
  '矛': '矛部',
  '矢': '矢部',
  '石': '石部',
  '示': '示部（礻）',
  '禸': '禸部',
  '禾': '禾部',
  '穴': '穴部',
  '立': '立部',
  '竹': '竹部（⺮）',
  '米': '米部',
  '糸': '絲旁（糹）',
  '缶': '缶部',
  '网': '网部',
  '羊': '羊部',
  '羽': '羽部',
  '老': '老部',
  '而': '而部',
  '耒': '耒部',
  '耳': '耳部',
  '聿': '聿部',
  '肉': '肉部（月）',
  '臣': '臣部',
  '自': '自部',
  '至': '至部',
  '臼': '臼部',
  '舌': '舌部',
  '舛': '舛部',
  '舟': '舟部',
  '艮': '艮部',
  '色': '色部',
  '艸': '草字頭（艹）',
  '虍': '虎部（虍）',
  '虫': '虫部',
  '血': '血部',
  '行': '行部',
  '衣': '衣部（衤）',
  '襾': '襾部',
  '見': '見部',
  '角': '角部',
  '言': '言部（訁）',
  '谷': '谷部',
  '豆': '豆部',
  '豕': '豕部',
  '豸': '豸部',
  '貝': '貝部',
  '赤': '赤部',
  '走': '走部',
  '足': '足部（⻊）',
  '身': '身部',
  '車': '車部',
  '辛': '辛部',
  '辰': '辰部',
  '辶': '走之底（辶）',
  '邑': '邑部（⻏）',
  '酉': '酉部',
  '釆': '釆部',
  '里': '里部',
  '金': '金部（釒）',
  '長': '長部',
  '門': '門部',
  '阜': '阜部（⻖）',
  '隶': '隶部',
  '隹': '隹部',
  '雨': '雨部',
  '青': '青部',
  '非': '非部',
  '面': '面部',
  '革': '革部',
  '韋': '韋部',
  '韭': '韭部',
  '音': '音部',
  '頁': '頁部',
  '風': '風部',
  '飛': '飛部',
  '食': '食部（飠）',
  '首': '首部',
  '香': '香部',
  '馬': '馬部',
  '骨': '骨部',
  '高': '高部',
  '髟': '髟部',
  '鬥': '鬥部',
  '鬯': '鬯部',
  '鬲': '鬲部',
  '鬼': '鬼部',
  '魚': '魚部',
  '鳥': '鳥部',
  '鹵': '鹵部',
  '鹿': '鹿部',
  '麥': '麥部',
  '麻': '麻部',
  '黃': '黃部',
  '黍': '黍部',
  '黑': '黑部',
  '黹': '黹部',
  '黽': '黽部',
  '鼎': '鼎部',
  '鼓': '鼓部',
  '鼠': '鼠部',
  '鼻': '鼻部',
  '齊': '齊部',
  '齒': '齒部',
  '龍': '龍部',
  '龜': '龜部',
  '龠': '龠部'
};


// ============================================================
// 擴展字典 — 精簡格式覆蓋更多常用字
// 格式: [粵拼, English, 中文意思, 部首]
// ============================================================
const CHAR_EXT = {
  // ── 人部 (亻) ──
  '仙': ['sin1','Immortal','神仙','人'],
  '代': ['doi6','Generation / Substitute','代替、年代','人'],
  '任': ['jam6','Duty / Appoint','任務','人'],
  '件': ['gin6','Piece / Item','一件','人'],
  '份': ['fan6','Portion / Share','份量','人'],
  '仔': ['zai2','Son / Small','仔','人'],
  '付': ['fu6','Pay','付款','人'],
  '休': ['jau1','Rest','休息','人'],
  '伸': ['san1','Stretch','伸展','人'],
  '似': ['ci5','Similar / Like','似乎','人'],
  '位': ['wai2','Position / Seat','位置','人'],
  '住': ['zyu6','Live / Reside','住','人'],
  '低': ['dai1','Low','低','人'],
  '佈': ['bou3','Announce / Spread','宣佈','人'],
  '佔': ['zim3','Occupy','佔領','人'],
  '估': ['gu2','Estimate','估計','人'],
  '伯': ['baak3','Uncle / Elder','伯伯','人'],
  '伴': ['bun6','Companion','伴侶','人'],
  '佩': ['pui3','Wear / Admire','佩服','人'],
  '依': ['ji1','Depend','依靠','人'],
  '侍': ['si6','Serve / Wait on','侍候','人'],
  '供': ['gung1','Supply','供應','人'],
  '侵': ['cam1','Invade','侵略','人'],
  '俊': ['zeon3','Handsome / Talented','俊俏','人'],
  '保': ['bou2','Protect','保護','人'],
  '修': ['sau1','Repair / Cultivate','修行','人'],
  '俗': ['zuk6','Custom / Vulgar','風俗','人'],
  '倒': ['dou2','Fall over / Pour','倒下','人'],
  '倍': ['pui5','Times / Double','倍數','人'],
  '候': ['hau6','Wait / Season','等候','人'],
  '借': ['ze3','Borrow / Lend','借','人'],
  '值': ['zik6','Value / Worth','價值','人'],
  '假': ['gaa2','Fake / Holiday','假期','人'],
  '偉': ['wai5','Great / Grand','偉大','人'],
  '偏': ['pin1','Biased / Lean','偏心','人'],
  '停': ['ting4','Stop','停止','人'],
  '健': ['gin6','Healthy','健康','人'],
  '側': ['zak1','Side','側面','人'],
  '傑': ['git6','Outstanding','傑出','人'],
  '傳': ['cyun4','Pass on / Legend','傳說','人'],
  '傷': ['soeng1','Hurt / Wound','受傷','人'],
  '僅': ['gan2','Merely / Only','僅僅','人'],
  '像': ['zoeng6','Image / Resemble','好像','人'],
  '價': ['gaa3','Price','價錢','人'],
  '儀': ['ji4','Ceremony / Instrument','儀式','人'],
  '億': ['jik1','Hundred million','一億','人'],
  '優': ['jau1','Excellent','優秀','人'],
  '償': ['soeng4','Compensate','賠償','人'],
  '儲': ['cyu5','Save / Store','儲蓄','人'],

  // ── 口部 ──
  '叫': ['giu3','Call / Shout','叫','口'],
  '句': ['geoi3','Sentence','句子','口'],
  '各': ['gok3','Each','各個','口'],
  '合': ['hap6','Combine / Fit','合作','口'],
  '向': ['hoeng3','Toward / Direction','方向','口'],
  '吐': ['tou3','Spit / Vomit','吐','口'],
  '吸': ['kap1','Absorb / Inhale','吸收','口'],
  '吹': ['ceoi1','Blow','吹','口'],
  '吵': ['caau2','Noisy / Quarrel','嘈吵','口'],
  '味': ['mei6','Taste / Flavor','味道','口'],
  '呼': ['fu1','Call / Breathe','呼吸','口'],
  '咬': ['ngaau5','Bite','咬','口'],
  '品': ['ban2','Product / Grade','品質','口'],
  '哭': ['huk1','Cry','喊','口'],
  '唐': ['tong4','Tang dynasty','唐朝','口'],
  '唱': ['coeng3','Sing','唱歌','口'],
  '商': ['soeng1','Business / Discuss','商業','口'],
  '啟': ['kai2','Open / Start','啟動','口'],
  '嘆': ['taan3','Sigh','嘆息','口'],
  '嘗': ['soeng4','Taste / Try','品嘗','口'],
  '嘴': ['zeoi2','Mouth / Lips','嘴巴','口'],
  '器': ['hei3','Utensil / Organ','器官','口'],
  '嚇': ['haak3','Scare','嚇','口'],
  '嚴': ['jim4','Strict / Severe','嚴格','口'],
  '囚': ['cau4','Prisoner','囚犯','囗'],
  '圍': ['wai4','Surround','圍','囗'],
  '固': ['gu3','Solid / Firm','固定','囗'],
  '圈': ['hyun1','Circle / Ring','圈','囗'],
  '圖': ['tou4','Picture / Map','圖畫','囗'],
  '團': ['tyun4','Group / Ball','團體','囗'],
  '嘻': ['hei1','Ha / Playful','嘻嘻','口'],
  '吉': ['gat1','Lucky','吉祥','口'],
  '呀': ['aa1','(exclamation)','呀','口'],
  '吧': ['baa1','(particle)','吧','口'],
  '呢': ['ne1','(particle) / This','呢','口'],
  '哦': ['o4','Oh','哦','口'],
  '啊': ['aa3','Ah','啊','口'],
  '嗯': ['ng2','Hmm','嗯','口'],
  '嗰': ['go2','That (Cantonese)','嗰個','口'],
  '咗': ['zo2','(past tense, Canto)','咗','口'],
  '啲': ['di1','Some (Cantonese)','啲','口'],
  '咁': ['gam2','So / Like this','咁','口'],
  '嘢': ['je5','Thing (Cantonese)','嘢','口'],
  '噉': ['gam2','Like this (Canto)','噉','口'],
  '咪': ['mai5','Don\'t (Cantonese)','咪','口'],
  '喂': ['wai2','Hello (phone)','喂','口'],
  '喇': ['laa3','(particle)','喇','口'],

  // ── 水部 (氵) ──
  '汁': ['zap1','Juice / Sauce','汁','水'],
  '汗': ['hon6','Sweat','汗','水'],
  '江': ['gong1','River','江','水'],
  '池': ['ci4','Pool / Pond','池塘','水'],
  '汙': ['wu1','Dirty / Pollute','污染','水'],
  '沉': ['cam4','Sink / Heavy','沉','水'],
  '沒': ['mut6','Sink / Not have','沒有','水'],
  '沙': ['saa1','Sand','沙','水'],
  '油': ['jau4','Oil','油','水'],
  '沿': ['jyun4','Along','沿住','水'],
  '注': ['zyu3','Pour / Annotate','注意','水'],
  '泡': ['paau1','Bubble / Soak','泡','水'],
  '泥': ['nai4','Mud','泥','水'],
  '泳': ['wing6','Swim','游泳','水'],
  '洗': ['sai2','Wash','洗','水'],
  '洋': ['joeng4','Ocean / Foreign','海洋','水'],
  '洞': ['dung6','Cave / Hole','洞','水'],
  '洪': ['hung4','Flood','洪水','水'],
  '活': ['wut6','Live / Active','生活','水'],
  '流': ['lau4','Flow','流動','水'],
  '浪': ['long6','Wave','浪','水'],
  '浮': ['fau4','Float','浮','水'],
  '消': ['siu1','Disappear / Digest','消失','水'],
  '涼': ['loeng4','Cool','涼','水'],
  '淡': ['taam5','Light / Bland','淡','水'],
  '淚': ['leoi6','Tears','眼淚','水'],
  '清': ['cing1','Clear / Clean','清楚','水'],
  '減': ['gaam2','Reduce','減少','水'],
  '溫': ['wan1','Warm / Temperature','溫度','水'],
  '準': ['zeon2','Accurate / Allow','準備','水'],
  '滅': ['mit6','Extinguish','消滅','水'],
  '滑': ['waat6','Slippery / Slide','滑','水'],
  '漫': ['maan6','Overflow / Casual','漫畫','水'],
  '潔': ['git3','Clean / Pure','潔淨','水'],
  '潮': ['ciu4','Tide / Trendy','潮流','水'],
  '澤': ['zaak6','Marsh / Lustre','光澤','水'],
  '濃': ['nung4','Thick / Dense','濃','水'],
  '濕': ['sap1','Wet / Damp','濕','水'],
  '瀑': ['buk6','Waterfall','瀑布','水'],
  '液': ['jik6','Liquid','液體','水'],
  '涉': ['sip3','Wade / Involve','涉及','水'],
  '渡': ['dou6','Cross / Ferry','渡過','水'],
  '測': ['cak1','Measure / Test','測量','水'],
  '港': ['gong2','Harbour / HK','港口','水'],
  '游': ['jau4','Swim / Travel','游泳','水'],
  '湊': ['cau3','Gather / Bring up','湊仔','水'],
  '源': ['jyun4','Source / Origin','來源','水'],
  '溪': ['kai1','Stream / Creek','溪','水'],
  '滴': ['dik6','Drop','滴','水'],
  '漁': ['jyu4','Fishing','漁業','水'],
  '漂': ['piu1','Float / Bleach','漂亮','水'],
  '漆': ['cat1','Lacquer / Paint','油漆','水'],
  '演': ['jin2','Perform / Evolve','演出','水'],
  '漲': ['zoeng2','Rise (price)','漲價','水'],
  '潛': ['cim4','Dive / Hidden','潛水','水'],

  // ── 木部 ──
  '板': ['baan2','Board / Plank','板','木'],
  '杯': ['bui1','Cup','杯','木'],
  '枝': ['zi1','Branch','樹枝','木'],
  '架': ['gaa2','Frame / Shelf','架','木'],
  '柔': ['jau4','Soft / Gentle','柔軟','木'],
  '柱': ['cyu5','Pillar','柱','木'],
  '柳': ['lau5','Willow','柳樹','木'],
  '桃': ['tou4','Peach','桃','木'],
  '案': ['on3','Case / Desk','案件','木'],
  '桌': ['coek3','Table / Desk','桌','木'],
  '格': ['gaak3','Grid / Standard','格式','木'],
  '框': ['kwaang1','Frame','框','木'],
  '棄': ['hei3','Abandon','放棄','木'],
  '棉': ['min4','Cotton','棉花','木'],
  '棒': ['paang5','Stick / Great','棒','木'],
  '植': ['zik6','Plant','植物','木'],
  '椅': ['ji2','Chair','椅子','木'],
  '極': ['gik6','Extreme / Pole','極','木'],
  '概': ['koi3','General / Approximate','概念','木'],
  '構': ['kau3','Structure / Compose','結構','木'],
  '標': ['biu1','Mark / Standard','標準','木'],
  '樣': ['joeng6','Appearance / Kind','樣','木'],
  '模': ['mou4','Model / Pattern','模型','木'],
  '樹': ['syu6','Tree','樹','木'],
  '機': ['gei1','Machine / Chance','機會','木'],
  '橫': ['waang4','Horizontal','橫','木'],
  '檔': ['dong2','File / Block','檔案','木'],
  '檢': ['gim2','Check / Inspect','檢查','木'],
  '權': ['kyun4','Power / Right','權力','木'],
  '欄': ['laan4','Railing / Column','欄','木'],
  '杏': ['hang6','Apricot','杏','木'],
  '李': ['lei5','Plum / Surname','李','木'],
  '材': ['coi4','Material','材料','木'],
  '村': ['cyun1','Village','村','木'],
  '束': ['cuk1','Bundle / Restrain','束','木'],
  '條': ['tiu4','Strip / Clause','條','木'],
  '棵': ['fo1','(tree classifier)','棵','木'],
  '棘': ['gik1','Thorn','荊棘','木'],
  '業': ['jip6','Industry / Work','職業','木'],
  '榜': ['bong2','List / Placard','榜','木'],
  '榮': ['wing4','Glory / Honour','光榮','木'],
  '槍': ['coeng1','Gun / Spear','槍','木'],
  '樂': ['lok6','Joy / Music','快樂','木'],
  '樓': ['lau4','Building / Floor','大樓','木'],
  '橋': ['kiu4','Bridge','橋','木'],
  '檀': ['taan4','Sandalwood','檀香','木'],

  // ── 手部 (扌) ──
  '扶': ['fu4','Support','扶','手'],
  '找': ['zaau2','Look for','搵','手'],
  '技': ['gei6','Skill','技術','手'],
  '抓': ['zaa2','Grab / Catch','抓','手'],
  '抗': ['kong3','Resist','抗議','手'],
  '投': ['tau4','Throw / Vote','投票','手'],
  '折': ['zit3','Break / Fold','折','手'],
  '抱': ['pou5','Hold / Embrace','抱','手'],
  '押': ['aat3','Pledge / Escort','押','手'],
  '拉': ['laai1','Pull','拉','手'],
  '拋': ['paau1','Throw / Toss','拋','手'],
  '拍': ['paak3','Pat / Clap','拍','手'],
  '拒': ['keoi5','Refuse','拒絕','手'],
  '拔': ['bat6','Pull out','拔','手'],
  '招': ['ziu1','Beckon / Recruit','招','手'],
  '拜': ['baai3','Worship / Visit','拜拜','手'],
  '持': ['ci4','Hold / Maintain','堅持','手'],
  '指': ['zi2','Point / Finger','手指','手'],
  '按': ['on3','Press','按','手'],
  '挑': ['tiu1','Pick / Challenge','挑戰','手'],
  '振': ['zan3','Shake / Inspire','振作','手'],
  '捉': ['zuk1','Catch / Grasp','捉','手'],
  '捐': ['gyun1','Donate','捐款','手'],
  '捕': ['bou6','Catch / Arrest','捕捉','手'],
  '掌': ['zoeng2','Palm / Control','手掌','手'],
  '排': ['paai4','Row / Arrange','排列','手'],
  '掛': ['gwaa3','Hang','掛','手'],
  '採': ['coi2','Pick / Gather','採集','手'],
  '探': ['taam3','Explore / Visit','探險','手'],
  '接': ['zip3','Connect / Receive','接','手'],
  '控': ['hung3','Control','控制','手'],
  '推': ['teoi1','Push','推','手'],
  '描': ['miu4','Trace / Describe','描寫','手'],
  '插': ['caap3','Insert','插','手'],
  '換': ['wun6','Exchange','換','手'],
  '握': ['ak1','Grip / Hold','握','手'],
  '揮': ['fai1','Wave / Wield','揮','手'],
  '損': ['syun2','Damage / Loss','損失','手'],
  '搖': ['jiu4','Shake / Sway','搖','手'],
  '搜': ['sau2','Search','搜索','手'],
  '搬': ['bun1','Move / Carry','搬','手'],
  '搶': ['coeng2','Rob / Rush','搶','手'],
  '摸': ['mo2','Touch / Feel','摸','手'],
  '撐': ['caang1','Prop up','撐','手'],
  '撞': ['zong6','Crash / Hit','撞','手'],
  '播': ['bo3','Sow / Broadcast','播','手'],
  '擁': ['jung2','Embrace / Own','擁有','手'],
  '擊': ['gik1','Strike / Attack','攻擊','手'],
  '擔': ['daam1','Carry / Worry','擔心','手'],
  '據': ['geoi3','According to','根據','手'],
  '擦': ['caat3','Wipe / Rub','擦','手'],
  '舉': ['geoi2','Raise / Elect','舉手','手'],
  '拖': ['to1','Drag / Mop','拖','手'],
  '抽': ['cau1','Draw / Smoke','抽','手'],
  '披': ['pei1','Drape / Split','披','手'],
  '揀': ['gaan2','Choose (Canto)','揀','手'],
  '攝': ['sip3','Photograph','攝影','手'],

  // ── 心部 (忄) ──
  '忘': ['mong4','Forget','忘記','心'],
  '怪': ['gwaai3','Strange / Blame','怪','心'],
  '恆': ['hang4','Constant','恆心','心'],
  '恢': ['fui1','Restore','恢復','心'],
  '恥': ['ci2','Shame','恥辱','心'],
  '悅': ['jyut6','Pleased','愉悅','心'],
  '悔': ['fui3','Regret','後悔','心'],
  '悟': ['ng6','Realize','覺悟','心'],
  '患': ['waan6','Illness / Worry','患病','心'],
  '惜': ['sik1','Cherish / Pity','可惜','心'],
  '感': ['gam2','Feel / Sense','感覺','心'],
  '態': ['taai3','Attitude / State','態度','心'],
  '慈': ['ci4','Kind / Merciful','慈悲','心'],
  '慌': ['fong1','Flustered','慌張','心'],
  '慎': ['san6','Careful','謹慎','心'],
  '慣': ['gwaan3','Accustomed','習慣','心'],
  '慮': ['leoi6','Worry / Consider','考慮','心'],
  '慰': ['wai3','Comfort','安慰','心'],
  '慶': ['hing3','Celebrate','慶祝','心'],
  '憂': ['jau1','Worry / Sorrow','憂愁','心'],
  '憤': ['fan5','Angry / Indignant','憤怒','心'],
  '憶': ['jik1','Remember','記憶','心'],
  '懂': ['dung2','Understand','懂','心'],
  '懷': ['waai4','Embrace / Miss','懷念','心'],
  '懶': ['laan5','Lazy','懶','心'],
  '戀': ['lyun2','Love / Romance','戀愛','心'],
  '怕': ['paa3','Afraid','驚','心'],
  '急': ['gap1','Urgent / Anxious','急','心'],
  '性': ['sing3','Nature / Gender','性格','心'],
  '恨': ['han6','Hate','恨','心'],
  '悲': ['bei1','Sad / Tragedy','悲傷','心'],
  '惡': ['ok3','Evil / Bad','邪惡','心'],
  '惱': ['nou5','Annoyed','煩惱','心'],
  '愧': ['kwai3','Ashamed','慚愧','心'],
  '愿': ['jyun6','Willing','願意','心'],
  '慕': ['mou6','Admire','羨慕','心'],
  '憐': ['lin4','Pity','可憐','心'],
  '懼': ['geoi6','Fear','恐懼','心'],
  '懇': ['han2','Earnest','懇請','心'],
  '惠': ['wai6','Benefit / Kind','惠','心'],

  // ── 言部 (訁) ──
  '計': ['gai3','Plan / Calculate','計劃','言'],
  '訂': ['ding6','Order / Book','訂','言'],
  '記': ['gei3','Remember / Record','記住','言'],
  '訓': ['fan3','Train / Instruct','訓練','言'],
  '訊': ['seon3','Message / News','資訊','言'],
  '討': ['tou2','Discuss / Demand','討論','言'],
  '許': ['heoi2','Allow / Perhaps','許可','言'],
  '設': ['cit3','Set up / Design','設計','言'],
  '訪': ['fong2','Visit / Interview','訪問','言'],
  '證': ['zing3','Prove / Certificate','證明','言'],
  '評': ['ping4','Comment / Judge','評論','言'],
  '試': ['si5','Try / Test','考試','言'],
  '詐': ['zaa3','Cheat / Pretend','詐騙','言'],
  '詢': ['seon1','Inquire','諮詢','言'],
  '該': ['goi1','Should / That','應該','言'],
  '詳': ['coeng4','Detailed','詳細','言'],
  '認': ['jing6','Recognize / Admit','認識','言'],
  '誓': ['sai6','Swear / Oath','發誓','言'],
  '誘': ['jau5','Lure / Tempt','誘惑','言'],
  '誠': ['sing4','Sincere','誠實','言'],
  '誤': ['ng6','Mistake / Delay','錯誤','言'],
  '調': ['tiu4','Adjust / Tone','調整','言'],
  '談': ['taam4','Talk / Chat','談話','言'],
  '請': ['cing2','Please / Invite','請','言'],
  '論': ['leon6','Discuss / Theory','討論','言'],
  '課': ['fo3','Lesson / Class','課堂','言'],
  '諒': ['loeng6','Forgive','原諒','言'],
  '謀': ['mau4','Plan / Scheme','謀略','言'],
  '謎': ['mai4','Riddle / Mystery','謎語','言'],
  '謙': ['him1','Humble','謙虛','言'],
  '謝': ['ze6','Thank / Decline','多謝','言'],
  '謹': ['gan2','Cautious','謹慎','言'],
  '議': ['ji5','Discuss / Suggest','會議','言'],
  '護': ['wu6','Protect','保護','言'],
  '識': ['sik1','Know / Recognize','識','言'],
  '警': ['ging2','Police / Warn','警察','言'],
  '譯': ['jik6','Translate','翻譯','言'],
  '諾': ['nok6','Promise','承諾','言'],
  '讚': ['zaan3','Praise','讚','言'],

  // ── 金部 (釒) ──
  '針': ['zam1','Needle','針','金'],
  '釘': ['deng1','Nail','釘','金'],
  '鈴': ['ling4','Bell','鈴','金'],
  '鉄': ['tit3','Iron','鐵','金'],
  '鉛': ['jyun4','Lead (metal)','鉛','金'],
  '鋒': ['fung1','Edge / Sharp','鋒利','金'],
  '鋼': ['gong3','Steel','鋼鐵','金'],
  '錄': ['luk6','Record','記錄','金'],
  '錦': ['gam2','Brocade','錦繡','金'],
  '錯': ['co3','Wrong / Mistake','錯','金'],
  '鍋': ['wo1','Pot / Wok','鍋','金'],
  '鍛': ['dyun6','Forge / Temper','鍛煉','金'],
  '鍾': ['zung1','Bell / Surname','鍾','金'],
  '鎖': ['so2','Lock','鎖','金'],
  '鎮': ['zan3','Town / Suppress','鎮','金'],
  '鏡': ['geng3','Mirror','鏡','金'],
  '鐘': ['zung1','Clock / Bell','鐘','金'],
  '鐵': ['tit3','Iron','鐵','金'],
  '鑰': ['joek6','Key','鑰匙','金'],
  '鑽': ['zyun3','Drill / Diamond','鑽石','金'],

  // ── 火部 (灬) ──
  '灰': ['fui1','Ash / Grey','灰色','火'],
  '炒': ['caau2','Stir-fry','炒','火'],
  '炮': ['paau4','Cannon / Firecracker','炮','火'],
  '炸': ['zaa3','Fry / Explode','炸','火'],
  '烈': ['lit6','Fierce / Intense','猛烈','火'],
  '烏': ['wu1','Crow / Black','烏鴉','火'],
  '烘': ['hung1','Bake / Dry','烘','火'],
  '烤': ['haau1','Roast / Grill','烤','火'],
  '煙': ['jin1','Smoke / Cigarette','煙','火'],
  '煮': ['zyu2','Cook / Boil','煮','火'],
  '煩': ['faan4','Annoyed / Trouble','煩惱','火'],
  '照': ['ziu3','Shine / Photo','照片','火'],
  '熟': ['suk6','Ripe / Familiar','熟','火'],
  '熱': ['jit6','Hot','熱','火'],
  '燃': ['jin4','Burn','燃燒','火'],
  '燈': ['dang1','Lamp / Light','燈','火'],
  '燒': ['siu1','Burn / Roast','燒','火'],
  '爆': ['baau3','Explode','爆','火'],
  '爐': ['lou4','Stove / Furnace','爐','火'],
  '燦': ['caan3','Brilliant','燦爛','火'],
  '營': ['jing4','Camp / Operate','營業','火'],
  '烙': ['lok6','Brand / Bake','烙印','火'],

  // ── 土部 ──
  '均': ['gwan1','Equal / Even','均勻','土'],
  '坑': ['haang1','Pit / Hole','坑','土'],
  '坦': ['taan2','Flat / Calm','坦白','土'],
  '型': ['jing4','Type / Model','類型','土'],
  '埋': ['maai4','Bury / Approach','埋','土'],
  '域': ['wik6','Area / Domain','領域','土'],
  '培': ['pui4','Cultivate','培養','土'],
  '基': ['gei1','Base / Basic','基礎','土'],
  '堂': ['tong4','Hall','課堂','土'],
  '堅': ['gin1','Firm / Solid','堅持','土'],
  '堆': ['deoi1','Pile / Heap','堆','土'],
  '報': ['bou3','Report / Newspaper','報紙','土'],
  '場': ['coeng4','Field / Place','場地','土'],
  '塊': ['faai3','Piece / Chunk','一塊','土'],
  '塗': ['tou4','Smear / Paint','塗','土'],
  '塵': ['can4','Dust','灰塵','土'],
  '境': ['ging2','Border / Environment','環境','土'],
  '增': ['zang1','Increase','增加','土'],
  '壁': ['bik1','Wall','牆壁','土'],
  '壓': ['aat3','Press / Pressure','壓力','土'],
  '壞': ['waai6','Bad / Broken','壞','土'],
  '墓': ['mou6','Grave / Tomb','墓','土'],
  '墨': ['mak6','Ink','墨','土'],
  '壇': ['taan4','Altar / Forum','論壇','土'],

  // ── 日部 ──
  '旦': ['daan3','Dawn / Day','元旦','日'],
  '旨': ['zi2','Purpose / Decree','旨意','日'],
  '昆': ['kwan1','Elder brother','昆蟲','日'],
  '昏': ['fan1','Dusk / Faint','昏暗','日'],
  '映': ['jing2','Reflect / Project','反映','日'],
  '昨': ['zok6','Yesterday','昨日','日'],
  '普': ['pou2','Universal','普通','日'],
  '景': ['ging2','Scenery / Scene','風景','日'],
  '暑': ['syu2','Heat / Summer','暑假','日'],
  '暫': ['zaam6','Temporary','暫時','日'],
  '曆': ['lik6','Calendar','日曆','日'],
  '曉': ['hiu2','Dawn / Know','通曉','日'],
  '曲': ['kuk1','Song / Curve','歌曲','日'],
  '晨': ['san4','Morning','早晨','日'],
  '暴': ['bou6','Violent / Storm','暴風','日'],
  '曬': ['saai3','Sun-dry / Show off','曬','日'],
  '曾': ['cang4','Once / Surname','曾經','日'],
  '替': ['tai3','Replace','代替','日'],
  '晚': ['maan5','Evening / Late','夜晚','日'],
  '晝': ['zau3','Daytime','晝夜','日'],
  '暮': ['mou6','Dusk / Evening','暮色','日'],

  // ── 女部 ──
  '奶': ['naai5','Milk / Grandma','奶','女'],
  '妙': ['miu6','Wonderful','奇妙','女'],
  '妨': ['fong4','Hinder','妨礙','女'],
  '姑': ['gu1','Aunt / Girl','姑娘','女'],
  '姓': ['sing3','Surname','姓','女'],
  '委': ['wai2','Entrust','委員','女'],
  '姻': ['jan1','Marriage','婚姻','女'],
  '威': ['wai1','Power / Might','威風','女'],
  '娘': ['noeng4','Lady / Mother','娘','女'],
  '娛': ['jyu4','Entertain','娛樂','女'],
  '婆': ['po4','Grandmother','婆婆','女'],
  '婚': ['fan1','Marriage','結婚','女'],
  '媒': ['mui4','Medium / Media','媒體','女'],
  '媽': ['maa1','Mother','媽媽','女'],
  '嫁': ['gaa3','Marry (woman)','嫁','女'],
  '嫌': ['jim4','Dislike / Suspect','嫌棄','女'],
  '嬡': ['oi3','Daughter (polite)','千金','女'],
  '孕': ['jan6','Pregnant','懷孕','女'],
  '嫩': ['nyun6','Tender','嫩','女'],
  '孀': ['soeng1','Widow','孀','女'],

  // ── 糸部 (糹) ──
  '紀': ['gei2','Record / Era','世紀','糸'],
  '約': ['joek3','About / Promise','約定','糸'],
  '純': ['seon4','Pure','單純','糸'],
  '紛': ['fan1','Diverse / Dispute','紛紛','糸'],
  '素': ['sou3','Plain / Element','素食','糸'],
  '索': ['sok3','Search / Rope','索引','糸'],
  '細': ['sai3','Small / Detailed','細','糸'],
  '結': ['git3','Tie / Result','結果','糸'],
  '絕': ['zyut6','Absolute / Sever','絕對','糸'],
  '統': ['tung2','Unite / System','統一','糸'],
  '絡': ['lok3','Net / Connect','網絡','糸'],
  '綱': ['gong1','Outline / Key','大綱','糸'],
  '總': ['zung2','Total / General','總共','糸'],
  '緊': ['gan2','Tight / Urgent','緊張','糸'],
  '編': ['pin1','Edit / Weave','編輯','糸'],
  '緣': ['jyun4','Fate / Edge','緣份','糸'],
  '線': ['sin3','Line / Thread','線','糸'],
  '緩': ['wun6','Slow / Delay','緩慢','糸'],
  '縮': ['suk1','Shrink','縮小','糸'],
  '繁': ['faan4','Complex / Many','繁體','糸'],
  '繪': ['kui2','Draw / Paint','繪畫','糸'],
  '續': ['zuk6','Continue','繼續','糸'],
  '纏': ['cin4','Wrap / Tangle','纏繞','糸'],
  '織': ['zik1','Weave','組織','糸'],
  '繼': ['gai3','Continue / Inherit','繼續','糸'],
  '繩': ['sing4','Rope','繩','糸'],
  '纖': ['cim1','Fine / Slender','纖維','糸'],
  '組': ['zou2','Group / Organize','組織','糸'],

  // ── 竹部 (⺮) ──
  '笑': ['siu3','Laugh / Smile','笑','竹'],
  '符': ['fu4','Talisman / Match','符合','竹'],
  '第': ['dai6','(ordinal prefix)','第','竹'],
  '筋': ['gan1','Tendon / Muscle','筋','竹'],
  '等': ['dang2','Wait / Equal','等','竹'],
  '策': ['caak3','Plan / Whip','策略','竹'],
  '節': ['zit3','Festival / Joint','節日','竹'],
  '管': ['gun2','Tube / Manage','管理','竹'],
  '箱': ['soeng1','Box / Chest','箱','竹'],
  '範': ['faan6','Model / Scope','範圍','竹'],
  '篇': ['pin1','Chapter / Article','篇','竹'],
  '簡': ['gaan2','Simple / Brief','簡單','竹'],
  '簽': ['cim1','Sign / Stick','簽名','竹'],
  '籃': ['laam4','Basket','籃球','竹'],
  '籌': ['cau4','Plan / Chip','籌備','竹'],
  '籍': ['zik6','Registry','書籍','竹'],
  '築': ['zuk1','Build','建築','竹'],
  '算': ['syun3','Calculate','算','竹'],
  '箭': ['zin3','Arrow','箭','竹'],
  '筆': ['bat1','Pen / Brush','筆','竹'],

  // ── 石部 ──
  '破': ['po3','Break','破','石'],
  '研': ['jin4','Research / Grind','研究','石'],
  '確': ['kok3','Sure / Confirm','確定','石'],
  '碎': ['seoi3','Broken / Smash','碎','石'],
  '碗': ['wun2','Bowl','碗','石'],
  '碰': ['pung3','Touch / Bump','碰','石'],
  '磁': ['ci4','Magnet / Porcelain','磁','石'],
  '礎': ['co2','Foundation','基礎','石'],
  '磚': ['zyun1','Brick','磚','石'],
  '砲': ['paau4','Cannon','大砲','石'],
  '砂': ['saa1','Sand','砂','石'],

  // ── 虫部 ──
  '蛋': ['daan6','Egg','蛋','虫'],
  '蜂': ['fung1','Bee','蜜蜂','虫'],
  '蜜': ['mat6','Honey','蜜糖','虫'],
  '融': ['jung4','Melt / Blend','融合','虫'],
  '螢': ['jing4','Firefly','螢火蟲','虫'],
  '蟲': ['cung4','Insect / Bug','蟲','虫'],
  '蛙': ['waa1','Frog','青蛙','虫'],
  '蟻': ['ngai5','Ant','螞蟻','虫'],
  '蠟': ['laap6','Wax','蠟燭','虫'],

  // ── 衣部 (衤) ──
  '衝': ['cung1','Charge / Rush','衝','行'],
  '補': ['bou2','Mend / Supplement','補','衣'],
  '裁': ['coi4','Cut / Judge','裁判','衣'],
  '裂': ['lit6','Crack / Split','裂開','衣'],
  '裝': ['zong1','Install / Dress','裝','衣'],
  '裕': ['jyu6','Abundant','富裕','衣'],
  '製': ['zai3','Make / Produce','製造','衣'],
  '複': ['fuk1','Complex / Repeat','複雜','衣'],
  '襲': ['zaap6','Attack / Inherit','襲擊','衣'],
  '褲': ['fu3','Trousers','褲','衣'],
  '裙': ['kwan4','Skirt','裙','衣'],
  '袋': ['doi6','Bag / Pocket','袋','衣'],
  '被': ['bei6','Quilt / By (passive)','被','衣'],
  '襯': ['can3','Lining / Match','襯衫','衣'],

  // ── 貝部 ──
  '貨': ['fo3','Goods','貨物','貝'],
  '販': ['faan3','Sell / Vendor','販賣','貝'],
  '貢': ['gung3','Tribute','貢獻','貝'],
  '貴': ['gwai3','Expensive / Noble','貴','貝'],
  '買': ['maai5','Buy','買','貝'],
  '賣': ['maai6','Sell','賣','貝'],
  '費': ['fai3','Fee / Spend','費用','貝'],
  '賀': ['ho6','Congratulate','賀','貝'],
  '資': ['zi1','Capital / Resource','資源','貝'],
  '賓': ['ban1','Guest','賓客','貝'],
  '賞': ['soeng2','Reward / Appreciate','欣賞','貝'],
  '賠': ['pui4','Compensate','賠償','貝'],
  '賢': ['jin4','Wise / Virtuous','賢','貝'],
  '質': ['zat1','Quality / Matter','質素','貝'],
  '購': ['kau3','Purchase','購買','貝'],
  '賽': ['coi3','Race / Contest','比賽','貝'],
  '賜': ['ci3','Bestow','賜予','貝'],
  '賴': ['laai6','Depend / Blame','依賴','貝'],

  // ── 足部 (⻊) ──
  '跌': ['dit3','Fall / Drop','跌倒','足'],
  '跑': ['paau2','Run','跑步','足'],
  '跟': ['gan1','Follow / Heel','跟住','足'],
  '跡': ['zik1','Trace / Track','痕跡','足'],
  '跳': ['tiu3','Jump','跳','足'],
  '踏': ['daap6','Step on','踏','足'],
  '蹤': ['zung1','Trace / Trail','蹤跡','足'],
  '蹲': ['deon1','Squat','蹲','足'],
  '踢': ['tek3','Kick','踢','足'],
  '路': ['lou6','Road','路','足'],
  '距': ['keoi5','Distance','距離','足'],

  // ── 頁部 ──
  '頂': ['ding2','Top / Carry on head','頂','頁'],
  '項': ['hong6','Item / Nape','項目','頁'],
  '順': ['seon6','Smooth / Along','順','頁'],
  '須': ['seoi1','Must / Beard','必須','頁'],
  '預': ['jyu6','In advance','預備','頁'],
  '領': ['ling5','Lead / Collar','領導','頁'],
  '頻': ['pan4','Frequent','頻繁','頁'],
  '題': ['tai4','Topic / Problem','題目','頁'],
  '額': ['ngaak6','Forehead / Amount','額','頁'],
  '顏': ['ngaan4','Face / Colour','顏色','頁'],
  '願': ['jyun6','Wish / Willing','願望','頁'],
  '顧': ['gu3','Care / Look after','照顧','頁'],
  '顯': ['hin2','Obvious / Show','顯示','頁'],
  '類': ['leoi6','Type / Category','類別','頁'],

  // ── 食部 (飠) ──
  '飢': ['gei1','Hungry','飢餓','食'],
  '飲': ['jam2','Drink','飲','食'],
  '飽': ['baau2','Full (stomach)','飽','食'],
  '飾': ['sik1','Decorate','裝飾','食'],
  '養': ['joeng5','Raise / Nourish','養','食'],
  '餐': ['caan1','Meal','餐','食'],
  '餘': ['jyu4','Remaining','其餘','食'],
  '館': ['gun2','Hall / Hotel','博物館','食'],
  '餃': ['gaau2','Dumpling','餃子','食'],
  '餅': ['beng2','Cake / Biscuit','餅','食'],
  '餓': ['ngo6','Hungry','肚餓','食'],

  // ── 車部 ──
  '軌': ['gwai2','Track / Rail','軌道','車'],
  '較': ['gaau3','Compare','比較','車'],
  '輕': ['heng1','Light (weight)','輕','車'],
  '輝': ['fai1','Shine / Radiance','光輝','車'],
  '輩': ['bui3','Generation','前輩','車'],
  '輪': ['leon4','Wheel / Take turns','輪','車'],
  '輸': ['syu1','Lose / Transport','輸','車'],
  '轉': ['zyun3','Turn / Transfer','轉','車'],
  '轟': ['gwang1','Boom / Blast','轟','車'],
  '載': ['zoi3','Carry / Year','載','車'],
  '輛': ['loeng6','(vehicle clf.)','輛','車'],

  // ── 門部 ──
  '閃': ['sim2','Flash / Dodge','閃','門'],
  '閉': ['bai3','Close / Shut','閉','門'],
  '閒': ['haan4','Idle / Leisure','閒','門'],
  '閱': ['jyut6','Read / Review','閱讀','門'],
  '闊': ['fut3','Wide / Rich','闊','門'],
  '闢': ['pik1','Open up','開闢','門'],
  '閣': ['gok3','Chamber / Cabinet','閣','門'],
  '闖': ['cong2','Rush in','闖','門'],

  // ── 示部 (礻) ──
  '社': ['se5','Society','社會','示'],
  '祖': ['zou2','Ancestor','祖先','示'],
  '祝': ['zuk1','Wish / Bless','祝福','示'],
  '禁': ['gam3','Forbid','禁止','示'],
  '禍': ['wo6','Disaster','禍','示'],
  '禱': ['tou2','Pray','祈禱','示'],
  '祈': ['kei4','Pray','祈禱','示'],
  '祕': ['bei3','Secret','秘密','示'],
  '祥': ['coeng4','Auspicious','吉祥','示'],

  // ── 疒部 ──
  '疑': ['ji4','Doubt','懷疑','疋'],
  '疫': ['jik6','Epidemic','疫情','疒'],
  '疲': ['pei4','Tired','疲倦','疒'],
  '疼': ['tang4','Ache / Love','疼','疒'],
  '病': ['beng6','Sick / Disease','病','疒'],
  '症': ['zing3','Symptom','症狀','疒'],
  '痕': ['han4','Trace / Itchy','痕','疒'],
  '痛': ['tung3','Pain','痛','疒'],
  '療': ['liu4','Treat / Cure','治療','疒'],
  '瘋': ['fung1','Crazy','瘋狂','疒'],
  '癌': ['ngaam4','Cancer','癌症','疒'],
  '醫': ['ji1','Doctor / Medicine','醫生','酉'],
  '藥': ['joek6','Medicine / Drug','藥','艸'],

  // ── 禾部 ──
  '私': ['si1','Private','私人','禾'],
  '利': ['lei6','Sharp / Benefit','利益','刀'],
  '科': ['fo1','Subject / Branch','科學','禾'],
  '秒': ['miu5','Second','秒','禾'],
  '秘': ['bei3','Secret','秘密','禾'],
  '租': ['zou1','Rent','租','禾'],
  '程': ['cing4','Journey / Process','過程','禾'],
  '稅': ['seoi3','Tax','稅','禾'],
  '種': ['zung2','Seed / Type','種類','禾'],
  '稱': ['cing1','Call / Weigh','稱呼','禾'],
  '穩': ['wan2','Steady / Stable','穩定','禾'],
  '穀': ['guk1','Grain','穀物','禾'],
  '積': ['zik1','Accumulate','積累','禾'],
  '移': ['ji4','Move / Shift','移動','禾'],
  '稀': ['hei1','Rare / Thin','稀少','禾'],

  // ── 其他常用字 ──
  '互': ['wu6','Mutual','互相','二'],
  '井': ['zeng2','Well','井','二'],
  '亮': ['loeng6','Bright','明亮','亠'],
  '京': ['ging1','Capital','北京','亠'],
  '亡': ['mong4','Die / Flee','死亡','亠'],
  '交': ['gaau1','Exchange','交','亠'],
  '亦': ['jik6','Also','亦','亠'],
  '享': ['hoeng2','Enjoy','享受','亠'],
  '兆': ['siu6','Omen / Mega','兆','儿'],
  '充': ['cung1','Fill / Sufficient','充滿','儿'],
  '克': ['hak1','Overcome / Gram','克服','儿'],
  '免': ['min5','Avoid / Free','免費','儿'],
  '典': ['din2','Classic / Canon','經典','八'],
  '冊': ['caak3','Book / Volume','冊','冂'],
  '冒': ['mou6','Brave / Emit','冒險','冂'],
  '凍': ['dung3','Frozen / Cold','凍','冫'],
  '凝': ['jing4','Condense','凝結','冫'],
  '列': ['lit6','Row / List','列','刀'],
  '判': ['pun3','Judge','判斷','刀'],
  '則': ['zak1','Rule / Then','規則','刀'],
  '創': ['cong3','Create','創造','刀'],
  '制': ['zai3','System / Control','制度','刀'],
  '劃': ['waak6','Plan / Draw','計劃','刀'],
  '副': ['fu3','Vice / Second','副','刀'],
  '劇': ['kek6','Drama / Intense','劇','刀'],
  '勢': ['sai3','Power / Trend','形勢','力'],
  '勤': ['kan4','Diligent','勤力','力'],
  '勵': ['lai6','Encourage','鼓勵','力'],
  '包': ['baau1','Wrap / Bag','包','勹'],
  '匹': ['pat1','Match / Horse','匹配','匚'],
  '區': ['keoi1','Area / District','區域','匚'],
  '協': ['hip3','Cooperate','協助','十'],
  '南': ['naam4','South','南','十'],
  '博': ['bok3','Rich / Broad','博物館','十'],
  '卻': ['koek3','But / Retreat','卻','卩'],
  '即': ['zik1','Immediately','即','卩'],
  '印': ['jan3','Print / Seal','印','卩'],
  '卷': ['gyun2','Scroll / Roll','卷','卩'],
  '厚': ['hau5','Thick','厚','厂'],
  '原': ['jyun4','Origin / Plain','原本','厂'],
  '厲': ['lai6','Severe / Sharp','厲害','厂'],
  '參': ['caam1','Join / Ginseng','參加','厶'],
  '叔': ['suk1','Uncle','叔叔','又'],
  '反': ['faan2','Oppose / Return','反','又'],
  '取': ['ceoi2','Take / Get','取','又'],
  '受': ['sau6','Receive / Suffer','受','又'],
  '變': ['bin3','Change','變','又'],
  '雙': ['soeng1','Double / Pair','雙','又'],
  '發': ['faat3','Send / Develop','發展','弓'],
  '對': ['deoi3','Correct / Pair','對','寸'],
  '專': ['zyun1','Special / Expert','專門','寸'],
  '尊': ['zyun1','Respect','尊重','寸'],
  '導': ['dou6','Guide / Lead','導演','寸'],
  '封': ['fung1','Seal / Envelope','封','寸'],
  '射': ['se6','Shoot','射','寸'],
  '局': ['guk6','Bureau / Game','局','尸'],
  '居': ['geoi1','Live / Reside','居住','尸'],
  '展': ['zin2','Unfold / Exhibit','展覽','尸'],
  '層': ['cang4','Layer / Floor','層','尸'],
  '屆': ['gaai3','Session','屆','尸'],
  '屬': ['suk6','Belong / Category','屬於','尸'],
  '差': ['caa1','Difference','差','工'],
  '巨': ['geoi6','Huge','巨大','工'],
  '巧': ['haau2','Clever / Skill','巧妙','工'],
  '市': ['si5','City / Market','市場','巾'],
  '布': ['bou3','Cloth','布','巾'],
  '帶': ['daai3','Belt / Bring','帶','巾'],
  '幕': ['mok6','Screen / Curtain','幕','巾'],
  '幫': ['bong1','Help','幫助','巾'],
  '幹': ['gon3','Do / Trunk','幹','干'],
  '平': ['ping4','Flat / Peace','平安','干'],
  '年': ['nin4','Year','年','干'],
  '幸': ['hang6','Lucky','幸運','干'],
  '幼': ['jau3','Young','幼稚','幺'],
  '床': ['cong4','Bed','床','广'],
  '度': ['dou6','Degree / Time','度','广'],
  '座': ['zo6','Seat / (clf.)','座位','广'],
  '庫': ['fu3','Warehouse','倉庫','广'],
  '庭': ['ting4','Court / Garden','家庭','广'],
  '康': ['hong1','Health','健康','广'],
  '廢': ['fai3','Waste / Abolish','廢','广'],
  '廣': ['gwong2','Wide / Broad','廣州','广'],
  '建': ['gin3','Build','建設','廴'],
  '延': ['jin4','Delay / Extend','延長','廴'],
  '張': ['zoeng1','Open / Surname','張','弓'],
  '強': ['koeng5','Strong','強','弓'],
  '弱': ['joek6','Weak','弱','弓'],
  '彈': ['daan6','Bullet / Play','彈琴','弓'],
  '形': ['jing4','Shape / Form','形狀','彡'],
  '彩': ['coi2','Color / Prize','彩色','彡'],
  '影': ['jing2','Shadow / Movie','影','彡'],
  '役': ['jik6','Service / Battle','服役','彳'],
  '往': ['wong5','Go toward','往','彳'],
  '待': ['doi6','Wait / Treat','等待','彳'],
  '律': ['leot6','Law','法律','彳'],
  '徒': ['tou4','Apprentice / In vain','徒弟','彳'],
  '徑': ['ging3','Path / Directly','路徑','彳'],
  '復': ['fuk6','Recover / Again','恢復','彳'],
  '微': ['mei4','Tiny / Micro','微小','彳'],
  '徵': ['zing1','Collect / Sign','象徵','彳'],
  '戒': ['gaai3','Quit / Ring','戒指','戈'],
  '或': ['waak6','Or / Perhaps','或者','戈'],
  '截': ['zit6','Cut / Intercept','截','戈'],
  '戲': ['hei3','Play / Opera','戲劇','戈'],
  '房': ['fong4','Room','房間','戶'],
  '所': ['so2','Place / (particle)','所以','戶'],
  '扇': ['sin3','Fan','扇','戶'],
  '才': ['coi4','Talent','才能','手'],
  '效': ['haau6','Effect','效果','攴'],
  '故': ['gu3','Reason / Old','故事','攴'],
  '政': ['zing3','Politics','政治','攴'],
  '整': ['zing2','Whole / Tidy','整齊','攴'],
  '數': ['sou3','Number / Count','數學','攴'],
  '敵': ['dik6','Enemy','敵人','攴'],
  '料': ['liu6','Material','材料','斗'],
  '斷': ['tyun5','Break / Judge','判斷','斤'],
  '族': ['zuk6','Tribe / Race','民族','方'],
  '旅': ['leoi5','Travel','旅行','方'],
  '旗': ['kei4','Flag','旗','方'],
  '既': ['gei3','Already / Since','既然','無'],
  '望': ['mong6','Hope / Look','希望','月'],
  '期': ['kei4','Period / Expect','期限','月'],
  '服': ['fuk6','Clothes / Serve','衣服','月'],
  '歐': ['au1','Europe','歐洲','欠'],
  '歡': ['fun1','Joy / Happy','歡喜','欠'],
  '次': ['ci3','Time / Second','次','欠'],
  '歲': ['seoi3','Year (age)','歲','止'],
  '段': ['dyun6','Section / Stage','一段','殳'],
  '殺': ['saat3','Kill','殺','殳'],
  '毒': ['duk6','Poison','毒','母'],
  '比': ['bei2','Compare','比較','比'],
  '求': ['kau4','Request / Seek','要求','水'],
  '決': ['kyut3','Decide','決定','水'],
  '況': ['fong3','Situation','情況','水'],
  '泄': ['sit3','Leak','洩漏','水'],
  '版': ['baan2','Edition / Board','版本','片'],
  '牌': ['paai4','Card / Brand','牌','片'],
  '犯': ['faan6','Violate / Criminal','犯罪','犬'],
  '狀': ['zong6','Shape / Status','狀態','犬'],
  '狂': ['kwong4','Crazy','狂','犬'],
  '獨': ['duk6','Alone','獨自','犬'],
  '獲': ['wok6','Obtain','獲得','犬'],
  '獎': ['zoeng2','Prize / Award','獎','犬'],
  '獻': ['hin3','Offer / Dedicate','貢獻','犬'],
  '環': ['waan4','Ring / Circle','環境','王'],
  '現': ['jin6','Present / Appear','現在','王'],
  '球': ['kau4','Ball / Globe','地球','王'],
  '班': ['baan1','Class / Group','班','王'],
  '理': ['lei5','Reason / Manage','道理','王'],
  '琴': ['kam4','Zither','古琴','王'],
  '瑰': ['gwai1','Rose / Treasure','玫瑰','王'],
  '瓶': ['ping4','Bottle','瓶','瓦'],
  '甚': ['sam6','Very / What','甚至','甘'],
  '甜': ['tim4','Sweet','甜','甘'],
  '界': ['gaai3','World / Boundary','世界','田'],
  '留': ['lau4','Stay / Keep','留','田'],
  '略': ['loek6','Brief / Strategy','策略','田'],
  '番': ['faan1','Turn / Foreign','番','田'],
  '異': ['ji6','Different','異','田'],
  '當': ['dong1','When / Should','當','田'],
  '登': ['dang1','Climb / Register','登','田'],
  '盡': ['zeon6','Exhaust / All','盡','皿'],
  '盟': ['mang4','Alliance','同盟','皿'],
  '監': ['gaam1','Monitor / Prison','監','皿'],
  '盤': ['pun4','Plate / Disk','盤','皿'],
  '盜': ['dou6','Steal / Thief','盜','皿'],
  '省': ['saang2','Province / Save','省','目'],
  '盲': ['maang4','Blind','盲','目'],
  '督': ['duk1','Supervise','監督','目'],
  '睡': ['seoi6','Sleep','瞓覺','目'],
  '矛': ['maau4','Spear','矛盾','矛'],
  '端': ['dyun1','End / Proper','端','立'],
  '章': ['zoeng1','Chapter / Seal','章','立'],
  '童': ['tung4','Child','兒童','立'],
  '競': ['ging6','Compete','競爭','立'],
  '窮': ['kung4','Poor','窮','穴'],
  '窗': ['coeng1','Window','窗','穴'],
  '究': ['gau3','Investigate','研究','穴'],
  '突': ['dat6','Sudden','突然','穴'],
  '穿': ['cyun1','Wear / Through','穿','穴'],
  '興': ['hing1','Prosper / Interest','興趣','臼'],
  '舉': ['geoi2','Raise / Elect','舉','臼'],
  '般': ['bun1','Kind / Sort','一般','舟'],
  '船': ['syun4','Ship / Boat','船','舟'],
  '航': ['hong4','Navigate / Fly','航行','舟'],
  '艦': ['laam6','Warship','戰艦','舟'],
  '若': ['joek6','If / Like','若果','艸'],
  '苦': ['fu2','Bitter / Suffer','苦','艸'],
  '英': ['jing1','Brave / English','英文','艸'],
  '茫': ['mong4','Vast / Vague','茫然','艸'],
  '荒': ['fong1','Waste / Wild','荒','艸'],
  '華': ['waa4','China / Splendid','華','艸'],
  '落': ['lok6','Fall / Drop','落','艸'],
  '著': ['zoek6','Wear / Write','著','艸'],
  '蒸': ['zing1','Steam','蒸','艸'],
  '蔣': ['zoeng2','Surname Chiang','蔣','艸'],
  '薄': ['bok6','Thin','薄','艸'],
  '薪': ['san1','Salary','薪金','艸'],
  '藏': ['cong4','Hide / Store','收藏','艸'],
  '蘇': ['sou1','Revive / Surname','蘇','艸'],
  '處': ['cyu3','Place / Handle','處理','虍'],
  '號': ['hou6','Number / Name','號碼','虍'],
  '術': ['seot6','Art / Technique','技術','行'],
  '街': ['gaai1','Street','街','行'],
  '規': ['kwai1','Rule','規則','見'],
  '視': ['si6','Look / Vision','電視','見'],
  '覺': ['gok3','Feel / Aware','感覺','見'],
  '觀': ['gun1','Watch / View','觀察','見'],
  '角': ['gok3','Corner / Horn','角','角'],
  '解': ['gaai2','Solve / Untie','解決','角'],
  '觸': ['zuk1','Touch','觸','角'],
  '託': ['tok3','Entrust','委託','言'],
  '谷': ['guk1','Valley','谷','谷'],
  '負': ['fu6','Negative / Owe','負責','貝'],
  '貿': ['mau6','Trade','貿易','貝'],
  '越': ['jyut6','Cross / More','越來越','走'],
  '趁': ['can3','Take advantage','趁','走'],
  '趕': ['gon2','Chase / Rush','趕','走'],
  '趣': ['ceoi3','Interest / Fun','有趣','走'],
  '輔': ['fu6','Assist','輔助','車'],
  '辦': ['baan6','Handle / Do','辦公','力'],
  '辭': ['ci4','Words / Resign','辭職','辛'],
  '農': ['nung4','Farm','農業','辰'],
  '迎': ['jing4','Welcome','歡迎','辶'],
  '近': ['kan5','Near','附近','辶'],
  '述': ['seot6','State / Relate','描述','辶'],
  '迫': ['bik1','Force / Press','逼迫','辶'],
  '追': ['zeoi1','Chase','追','辶'],
  '退': ['teoi3','Retreat','退','辶'],
  '送': ['sung3','Send / Give','送','辶'],
  '逃': ['tou4','Escape','逃','辶'],
  '透': ['tau3','Through','透','辶'],
  '逐': ['zuk6','Chase / One by one','逐步','辶'],
  '途': ['tou4','Way / Route','途中','辶'],
  '通': ['tung1','Through / Connect','通過','辶'],
  '速': ['cuk1','Speed','速度','辶'],
  '造': ['zou6','Make / Create','製造','辶'],
  '連': ['lin4','Connect / Even','連','辶'],
  '週': ['zau1','Week','一週','辶'],
  '進': ['zeon3','Enter / Advance','進入','辶'],
  '遇': ['jyu6','Meet / Encounter','遇到','辶'],
  '運': ['wan6','Luck / Transport','運動','辶'],
  '過': ['gwo3','Pass / Exceed','過','辶'],
  '達': ['daat6','Reach','到達','辶'],
  '遊': ['jau4','Travel / Play','遊戲','辶'],
  '遙': ['jiu4','Distant','遙遠','辶'],
  '遣': ['hin2','Send / Dispatch','派遣','辶'],
  '遮': ['ze1','Block / Umbrella','遮','辶'],
  '遲': ['ci4','Late','遲到','辶'],
  '選': ['syun2','Choose / Elect','選擇','辶'],
  '避': ['bei6','Avoid','避開','辶'],
  '還': ['waan4','Still / Return','還','辶'],
  '邊': ['bin1','Side / Edge','邊','辶'],
  '配': ['pui3','Match / Assign','配合','酉'],
  '醉': ['zeoi3','Drunk','醉','酉'],
  '釋': ['sik1','Release / Explain','解釋','釆'],
  '里': ['lei5','Mile / Inside','里','里'],
  '量': ['loeng6','Measure / Amount','量','里'],
  '野': ['je5','Wild / Field','野','里'],
  '陪': ['pui4','Accompany','陪','阜'],
  '院': ['jyun2','Institute / Court','醫院','阜'],
  '陳': ['can4','Display / Surname','陳','阜'],
  '陸': ['luk6','Land','大陸','阜'],
  '陣': ['zan6','Battle array / Spell','陣','阜'],
  '除': ['ceoi4','Remove / Except','除咗','阜'],
  '陰': ['jam1','Shade / Yin','陰','阜'],
  '陽': ['joeng4','Sun / Yang','陽光','阜'],
  '隊': ['deoi6','Team / Queue','隊','阜'],
  '階': ['gaai1','Step / Stage','階段','阜'],
  '際': ['zai3','Border / Between','國際','阜'],
  '障': ['zoeng3','Barrier','障礙','阜'],
  '隨': ['ceoi4','Follow','隨便','阜'],
  '險': ['him2','Danger','危險','阜'],
  '隱': ['jan2','Hide','隱藏','阜'],
  '隻': ['zek3','(animal clf.)','隻','隹'],
  '集': ['zaap6','Collect','收集','隹'],
  '雄': ['hung4','Male / Hero','英雄','隹'],
  '雖': ['seoi1','Although','雖然','隹'],
  '雜': ['zaap6','Mix / Miscellaneous','雜','隹'],
  '難': ['naan4','Difficult','難','隹'],
  '震': ['zan3','Shake /震','地震','雨'],
  '霸': ['baa3','Tyrant / Dominate','霸','雨'],
  '靈': ['ling4','Spirit / Clever','靈','雨'],
  '革': ['gaak3','Leather / Reform','革命','革'],
  '鞋': ['haai4','Shoe','鞋','革'],
  '韻': ['wan5','Rhyme','韻','韭'],
  '響': ['hoeng2','Sound','響','音'],
  '頭': ['tau4','Head','頭','頁'],
  '飄': ['piu1','Float / Flutter','飄','風'],
  '首': ['sau2','Head / First','首先','首'],
  '驗': ['jim6','Verify / Experience','經驗','馬'],
  '驚': ['geng1','Shock / Afraid','驚','馬'],
  '體': ['tai2','Body / System','身體','骨'],
  '髮': ['faat3','Hair','頭髮','髟'],
  '鬧': ['naau6','Noisy / Trouble','鬧','鬥'],
  '魂': ['wan4','Soul','靈魂','鬼'],
  '鮮': ['sin1','Fresh','新鮮','魚'],
  '鯊': ['saa1','Shark','鯊魚','魚'],
  '鯨': ['king4','Whale','鯨魚','魚'],
  '鸚': ['jing1','Parrot','鸚鵡','鳥'],
  '麗': ['lai6','Beautiful','美麗','鹿'],
  '齊': ['cai4','Neat / Together','齊','齊'],

  // ── 科技 / 現代用字 ──
  '網': ['mong5','Net / Internet','網','糸'],
  '腦': ['nou5','Brain','腦','肉'],
  '電': ['din6','Electricity','電','雨'],
  '機': ['gei1','Machine','機器','木'],
  '態': ['taai3','State / Attitude','狀態','心'],
  '系': ['hai6','System','系統','糸'],
  '程': ['cing4','Process / Journey','程式','禾'],
  '資': ['zi1','Resource / Capital','資料','貝'],
  '訊': ['seon3','Message','資訊','言'],
  '碼': ['maa5','Code / Number','號碼','石'],
  '銀': ['ngan4','Silver','銀行','金'],
  '站': ['zaam6','Station / Stand','站','立'],
  '號': ['hou6','Number','號碼','虍'],

  // ── 粵語常用口語字 ──
  '冧': ['lam3','Flirt / Collapse','冧','冖'],
  '掟': ['deng2','Throw (Canto)','掟','手'],
  '攞': ['lo2','Take (Cantonese)','攞','手'],
  '嬲': ['nau1','Angry (Cantonese)','嬲','女'],
  '瞓': ['fan3','Sleep (Cantonese)','瞓覺','目'],
  '畀': ['bei2','Give (Cantonese)','畀','田'],
  '嚟': ['lei4','Come (Cantonese)','嚟','口'],
  '傾': ['king1','Chat (Cantonese)','傾計','人'],
  '諗': ['nam2','Think (Cantonese)','諗','言'],
  '搵': ['wan2','Find (Cantonese)','搵','手'],
  '揸': ['zaa1','Drive / Hold','揸車','手'],
  '鍾': ['zung1','Love (Cantonese)','鍾意','金'],
  '嘥': ['saai1','Waste (Cantonese)','嘥','口'],
  '唞': ['tau2','Rest (Cantonese)','唞氣','口'],
  '靚': ['leng3','Pretty (Cantonese)','靚','青'],

  // ── 補充常用字 ──
  '擇': ['zaak6','Choose / Select','選擇','手'],
  '戴': ['daai3','Wear (hat/glasses)','戴','戈'],
  '店': ['dim3','Shop / Store','商店','广'],
  '廳': ['teng1','Hall / Lounge','客廳','广'],
  '廠': ['cong2','Factory','工廠','广'],
  '慘': ['caam2','Miserable','慘','心'],
  '憾': ['ham6','Regret','遺憾','心'],
  '懲': ['cing4','Punish','懲罰','心'],
  '托': ['tok3','Entrust / Hold','托','手'],
  '抄': ['caau1','Copy / Raid','抄','手'],
  '抖': ['dau2','Tremble / Rest','抖','手'],
  '拆': ['caak3','Dismantle','拆','手'],
  '拼': ['ping3','Spell / Piece','拼','手'],
  '捨': ['se2','Give up','捨棄','手'],
  '掃': ['sou3','Sweep','掃','手'],
  '掘': ['gwat6','Dig','掘','手'],
  '揚': ['joeng4','Raise / Spread','揚','手'],
  '搭': ['daap3','Ride / Build','搭','手'],
  '摘': ['zaak6','Pick / Pluck','摘','手'],
  '撤': ['cit3','Withdraw','撤退','手'],
  '操': ['cou1','Operate / Exercise','操','手'],
  '擠': ['zai1','Squeeze / Crowd','擠','手'],
  '攪': ['gaau2','Stir / Mess up','攪','手'],
  '盒': ['hap6','Box / Case','盒','皿'],
  '蓋': ['goi3','Cover / Lid','蓋','艸'],
  '繫': ['hai6','Tie / Connect','繫','糸'],
  '聯': ['lyun4','Unite / Couplet','聯繫','耳'],
  '聲': ['seng1','Sound / Voice','聲音','耳'],
  '聽': ['teng1','Listen','聽','耳'],
  '職': ['zik1','Job / Post','職業','耳'],
  '肺': ['fai3','Lung','肺','肉'],
  '胃': ['wai6','Stomach','胃','肉'],
  '脂': ['zi1','Fat / Grease','脂肪','肉'],
  '脈': ['mak6','Pulse / Vein','脈搏','肉'],
  '腸': ['coeng4','Intestine','腸','肉'],
  '腰': ['jiu1','Waist','腰','肉'],
  '膽': ['daam2','Gall / Courage','膽','肉'],
  '臂': ['bei3','Arm','手臂','肉'],
  '咳': ['kat1','Cough','咳','口'],
  '嘔': ['au2','Vomit','嘔','口'],
  '噪': ['cou3','Noisy','噪音','口'],
  '圓': ['jyun4','Round / Circle','圓','囗'],
  '塔': ['taap3','Tower / Pagoda','塔','土'],
  '壽': ['sau6','Longevity','長壽','士'],
  '奇': ['kei4','Strange / Wonder','奇','大'],
  '奧': ['ou3','Profound / Olympic','奧','大'],
  '姿': ['zi1','Posture / Gesture','姿態','女'],
  '娃': ['waa1','Baby / Doll','娃娃','女'],
  '孫': ['syun1','Grandchild','孫','子'],
  '季': ['gwai3','Season / Quarter','季節','子'],
  '孤': ['gu1','Lonely / Orphan','孤獨','子'],
  '宇': ['jyu5','Universe','宇宙','宀'],
  '宙': ['zau6','Universe (time)','宇宙','宀'],
  '宗': ['zung1','Ancestor / Sect','宗教','宀'],
  '官': ['gun1','Official','官','宀'],
  '宜': ['ji4','Suitable','適宜','宀'],
  '客': ['haak3','Guest','客人','宀'],
  '宣': ['syun1','Announce','宣佈','宀'],
  '容': ['jung4','Contain / Face','容易','宀'],
  '密': ['mat6','Close / Secret','秘密','宀'],
  '富': ['fu3','Rich','富有','宀'],
  '寂': ['zik6','Quiet / Lonely','寂寞','宀'],
  '寒': ['hon4','Cold','寒冷','宀'],
  '審': ['sam2','Trial / Examine','審判','宀'],
  '寫': ['se2','Write','寫字','宀'],
  '寬': ['fun1','Wide / Tolerant','寬','宀'],
  '寶': ['bou2','Treasure','寶物','宀'],
  '察': ['caat3','Observe / Inspect','察覺','宀'],
  '寺': ['zi6','Temple','寺廟','寸'],
  '將': ['zoeng1','Will / General','將來','寸'],
  '尋': ['cam4','Seek / Search','尋找','寸'],
  '慧': ['wai6','Wise','智慧','心']
};
